### ISSUE TITLE
custom digit size, rather than a dropdown box?

### ISSUE THREAD

**Issue by magiruuvelvet** [paolostivanin/OTPClient#104]
in andOTP someone can enter any amount of digit size using free input. I'm aware your application is different, but shouldn't the library you use support any digit size (without limitation)?

Authy *native* tokens for example use 7 digits and they work great in andOTP. using 8 digits and than only enter the first 7 works too, but that's just irritating.

**Comment by paolostivanin** [comment]
Yup, that makes perfectly sense :) 
I'll add it for sure in v1.3.0

Thanks for reporting this :+1:
