### ISSUE TITLE
"No entries found in imported data" when importing into AndOTP

### ISSUE THREAD

**Issue by pizzadude** [paolostivanin/OTPClient#120]
I exported my database to encrypted json for AndOTP import, then when I imported it AndOTP displayed the error message "No entries found in imported data". So the export feature doesn't work (atleast for me).

**Comment by paolostivanin** [comment]
Hello,
thanks for reporting the issue.
When I tried before releasing v1.4 it worked fine. I'll have a look at it later today!

**Comment by paolostivanin** [comment]
I just tried and it worked perfectly for me (I have ~60 tokens).

I'm using OTPClient **1.4.0** (obviously :D) and andOTP **0.6.1**

**Comment by paolostivanin** [comment]
Your otpclient's db you mean? I don't think that's the problem, my dB was created when I was still developing the pre-alpha-v0.1 version :P
Anyway, that's an annoying bug and I'd like to understand what's going on. Some questions:
- do you have only totp or also hotp?
- do you have steam code?
- do you have empty label/issuer?
- how many tokens?

**Comment by pizzadude** [comment]
I have only TOTP. I don't have a steam code. Almost all the entries have empty Issuer. I have around 30 tokens.

**Comment by paolostivanin** [comment]
Ok ...so let's try this:
1) please fill all empty labels and issuers, then export and import.
If this still doesn't work, then we are only left with:
2) I'll write some code to help us debug the issue, but you will have to compile it yourself (are u familiar with such things?)

**Comment by pizzadude** [comment]
Sorry for long wait to reply. I couldn't fill in any of the empty labels as the issuer field is greyed out.

**Comment by paolostivanin** [comment]
That's really weird :thinking: 
Could you please give me an example token from your db? Just the label, issuer, type info are enough.

**Comment by pizzadude** [comment]
Example:
Type: TOTP
Label: Humble Bundle
Issuer: Blank (and can't fill it in)

Please note I exported this from Authy using a third party script.

**Comment by paolostivanin** [comment]
Mmm what was the script? Maybe it changed something in the format...
A question: in OTPClient did you import the andOTP export or the export created by the script?

**Comment by pizzadude** [comment]
The script:
https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93

More specifically, this version:
https://pastebin.com/raw/GLWg0ZMF

Answer to your question: I imported the andOTP export.

**Comment by paolostivanin** [comment]
It's really weird that you can't edit the issuer and importing the data. I really can't reproduce your issues :(
I guess we're left with creating a "debug branch" that you'll have to compile and execute yourself from terminal. I'll ping when this will be ready

**Comment by paolostivanin** [comment]
@pizzadude I have created https://github.com/paolostivanin/OTPClient/tree/debug-120 for debugging this issue. Could you please export your database? Using this branch:
- the database will be exported to an **unencrypted json** file
- the secret **won't be exported**, but will be **replaced** by a custom value

If you are ok with this, please send me the "cleaned" json (also via email if you prefer)

**Comment by pizzadude** [comment]
Sure, I just have to build it first.

**Comment by pizzadude** [comment]
Here's something I noticed after exporting. All the ones that were imported from andotp (originally created by the authy export script) were incorrectly labeled as "STEAM", even though they aren't for steam at all. In the GUI itself, it shows "TOTP" which is how it should be. I'll email you a redacted json soon.

**Comment by pizzadude** [comment]
Btw, I tried sending an email to your " info @ yourname " address, and my mail client wasn't sending it, so let me know if you got the email either more than once or not at all.

**Comment by paolostivanin** [comment]
* That's interesting! This explains why the issuer can't be edited :)
* Question is: why were all the tokens of type STEAM? I guess something went wrong the 3rd party script.
* The GUI shows `TOTP` because a steam code is a TOTP, but with a different workflow (who likes _standards_ eh Blizzard...). Usually one can recognize a Steam code because the issuer is forced to Steam but, for whatever reason, this is not happening to you
* no, I didn't receive any email

**Comment by pizzadude** [comment]
I re-sent the email to info at paolostivanin dot com  (email is from my github username + dotca at gmail)

**Comment by paolostivanin** [comment]
I see 2 weird things in that json:
* something has 7 as digits (weird, usually it's either 6 or 8 [steam 5])
* all the STEAM objects have no label and no issuer

My 2c is that something went bad with that js script that you posted above.
Anyway, as I wrote in the email it's best if I develop a small tool to clean this mess up. The workflow would then be:
1. decrypt the db using the tool
2. using your favorite editor, open the file and clean the db (eg add label, replace steam with totp, etc)
3. using the tool, encrypt the db again
4. replace the old 'corrupted' db with the new one

**Comment by paolostivanin** [comment]
@pizzadude I wrote a simple tool that will let you decrypt and encrypt the database, so you can easily edit it. Please note that the decrypted output file will be stored **in plain text in the /tmp folder**. I suggest you do that in a VM or in a live CD :+1: 
- `git clone https://github.com/paolostivanin/OTPClient -b debug-120`
- `cd OTPClient`
- `chmod +x build.sh`
- `./build.sh`
- `./otpclient_debug -d PATH-TO-OTPCLIENT-DB`
- edit the file `/tmp/otpclient_db_plaintext.json`
  - replace all `STEAM` occurrences with `TOTP`
  - add `label` where missing
- `./otpclient_debug -e /tmp/otpclient_db.enc`
- backup your current otpclient db
- move `/tmp/otpclient_db.enc` to PATH-TO-OTPCLIENT-DB

**Comment by pizzadude** [comment]
Thanks, I'll try that it later today or tomorrow.

**Comment by pizzadude** [comment]
@paolostivanin Sadly, it doesn't build.

Terminal output: https://pastebin.com/raw/z4VDka5H

**Comment by pizzadude** [comment]
@paolostivanin Sadly it doesn't build.

Terminal output: https://pastebin.com/raw/z4VDka5H

**Comment by paolostivanin** [comment]
Are you using `build.sh` to build the sources? If yes, then you are missing all the devel deps.
For openSUSE, for example, you should install `gtk3-devel` and `libgcrypt-devel`

**Comment by pizzadude** [comment]
Yes, I'm using build.sh to build it. I was able to build the first debug version. I followed your steps exactly as you wrote them, and I have installed all the build deps ( I just double checked ) otherwise I wouldn't be able to build AndOTP to export the json.

**Comment by pizzadude** [comment]
Maybe it would be easier to just release a non-debug branch feature that allows you to export the json unencrypted for manual fixing and give a warning about exporting it unencrypted it first?

**Comment by paolostivanin** [comment]
It's really weird that you can't build it :thinking: 
However, I've built for you the binary, I hope it works on your machine (I'm using openSUSE Leap 15 x86_64).

[otpclient_debug.zip](https://github.com/paolostivanin/OTPClient/files/3042212/otpclient_debug.zip)

Download, extract and follow the guide I wrote above. I'm a bit reluctant about implementing the unencrypted export. I'll have to think about it :+1:

**Comment by pizzadude** [comment]
Okay, I'm thinking you're probably gonna laugh at me and tell me how I'm an idiot for dealing with unencrypted json files like this. But I trust the systems I run, and while I didn't fix the issue of importing the database into AndOTP the normal way , I was able to copy the database manually to AndOTP through a very long and boring (and insecure by your standards process).

First off, the reason I had to do this was because your instructions didn't work. Your tool ran, it decrypted the database, but when I tried re-encrypting it after editing it multiple times, OTPClient would act like it didn't exist.

So, me being the adventurous type, I took the json that your previous tool exported for debugging, that was a censored AndOTP json, and I filled in the fields of the label and secret from the exported database that your new tool generated. (which took forever) I then sent the unencrypted json that I manually edited to my phone ( gasp ) and imported it to AndOTP, then I had to manually re-edit the labels inside AndOTP, because I assume AndOTP doesn't work with issuers (not sure, for some reason the template had two label fields, so I assumed that AndOTP counts issuers as a label also). After that, I backed up AndOTP's database to encrypted backup, imported it into a new OTPClient database, which worked. I then tried to export it from OTPClient and then import the encrypted json generated by OTPClient back into AndOTP, which gave me the same error that I started this bug report with. LOL

Also, for some reason in the the unencrypted OTPClient json that your new tool generates, there's no "STEAM" types. It's all TOTP, which is correct. I'm as confused as you might be. Or maybe you know why. I don't know.

**Comment by pizzadude** [comment]
Anyways, it would be really nice if you would add an unencrypted json backup feature, as I seem to get "decryption failed" every time I try to import any encrypted json that OTPClient generates into AndOTP, no matter how much I manually fix it. Maybe put a big scary warning or make it necessary to manually edit the config file to allow it, hiding it from the GUI?

**Comment by paolostivanin** [comment]
Created #125
