### ISSUE TITLE
Missing shortcut to quit the application

### ISSUE THREAD

**Issue by glitsj16** [paolostivanin/OTPClient#128]
Hi, this great application has loads of shortcuts, but I'm missing `Ctrl+Q` for `quit` in particular. As it's what most programs support I got used to closing opened windows with a keyboard that way. Would be nice if this could be added.

**Comment by paolostivanin** [comment]
Thanks for the suggestion! I'll add it this week :)

**Comment by glitsj16** [comment]
The Ctrl+Q shortcut works great after fixing a typo in your commit (see PR #131). Thanks again for adding it.

**Comment by paolostivanin** [comment]
Good catch :) thanks!!
