### ISSUE TITLE
add CLI 

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#137]
Currently, there's no way to use OTPClient on a system without a desktop environment (e.g. server).
As many of you asked for this feature, I'm gonna go ahead and implement it. This will take some time though because the implementation most likely will involve some refactoring.

- [x] design
  - part of `v2.0`
  - simple terminal interface
- [x] implementation
  - [x] `show` option
  - [x] `list` option
- [x] testing

**Comment by tentator** [comment]
I'm a big supporter of this feature! :)
And if I can help I will happily do.
In my view the best would be a simple terminal interface via regular command line parameters, no ncurses should be needed (of course there will be limitations for importing, e.g. no webcam scanning :))

**Comment by paolostivanin** [comment]
Help is always appreciated 😄 currently, I don't have a clear idea about how to implement this feature. The only sure thing is that I have to refactor the existing code because it's tightly coupled to GTK+ at the moment.
I will write here once this feature is ready to be implemented and, therefore, contributors can start helping 👍

**Comment by paolostivanin** [comment]
`otpclient-cli` will have the following options:
- `version`
- `help`
- `add`
- `remove`
- `list`
- `show`
- `edit`
- `import`
- `export`

The `add` option will accept the following parameters:
- `-t`(type): optional, default to TOTP (can be either TOTP or HOTP)
- `-h`(hash): optional, default to SHA1 (can be either one of SHA1, SHA256, SHA512)
- `-a` (account): mandatory
- `-i` (issuer): optional, default to empty string
- `-d` (digits): optional, default to 6
- `-p` (period): optional, default to 30
- `-c` (counter): mandatory if HOTP
- `-x`: show secret when typing it

Example:
`otpclient-cli add -t TOTP -h SHA1 -a testAccount -i myself -d 6 -p 30`
Same as above, but without using all the optional args:
`otpclient-cli add -a testAccount -i myself`
Once 'enter' is hit, a prompt will ask for the secret:
Type secret: **** (hidden by default, can be displayed with `-x`)

----------------------------------

The `remove` option will accept the following parameters:
- `-a` (account): mandatory if issuer is not specified, optional otherwise
- `-i` (issuer): mandatory if account is not specified, optional otherwise
- `-m`: match exactly (only remove if given string is matched 1:1)

Example:
`otpclient-cli remove -a testAccount`
will look for all the entries which have 'testAccount' (case insensitive) as account name and show the following prompt:
```
The following entries have been found:
1) testAccount
2) testAccount2
3) TestAccOUNT
Type the number to remove: 2
Entry with account name 'testAccount2' has been removed
```

----------------------------------

The `list` option will simply list all the items in the following form:
```
Account | Issuer
testAccount, myself
testAccount2, myself2
...
```

----------------------------------

The `show` option will accept the following parameters:
- `-a` (account): mandatory if issuer is not specified, optional otherwise
- `-i` (issuer): mandatory if account is not specified, optional otherwise
- `-m`: match exactly (only output if given string is matched)

Example:
`otpclient-cli show -a testAccount`
```
The following entries have been found:
1) testAccount
2) testAccount2
3) TestAccOUNT
Type the number to show: 2
Account:    testAccount2
Issuer:     myself2
OTP:        234123
Validity:   19s
```

----------------------------------

The `edit` option will accept the following parameters:
- `-a` (account): mandatory if issuer is not specified, optional otherwise
- `-i` (issuer): mandatory if account is not specified, optional otherwise
- `-m`: match exactly (only output if given string is matched)

Example:
`otpclient-cli edit -a testAccount`
```
New account: testAcc1
New issuer (leave empty for none): myself2
Successfully renamed account 'testAccount' => 'testAcc1' and issuer 'myself' => 'myself2'
```

----------------------------------

The `import` option will accept the following parameters:
- `-p` (provider): mandatory, can be either authplus or andotp
- `-f` (file): path to file

Example:
`otpclient-cli import -p andotp -f /tmp/otp_accounts.json.aes`
```
Type decryption password: ******
X items successfully imported.
```

----------------------------------

The `export` option will accept the following parameters:
- `-p` (provider): mandatory, can be either authplus or andotp
- `-f` (file): optional. By default, the file is saved into the `$HOME` directory

Example:
`otpclient-cli export -p andotp`
```
Data successfully exported and saved to $HOME/andotp_export.json.aes
```

What do you think? Any feedback about this design?

**Comment by tentator** [comment]
I like the proposed idea a lot!
If I understand it correctly, you would be able to get the next token by issuing: "otpclient-cli show -a testAccount" directly, with no interactive selection, right?

Another minor question : is it possible to see also the currently displaying token sequence number?

And thanks!

**Comment by paolostivanin** [comment]
* `otpclient-cli show -a testAccount` would show the current valid OTP value
* `otpclient-cli show -a testAccount` will require no input if there are no other matching accounts (testACCOUNT, teSTaccOunt, etc). Otherwise, you have to use `-m` if you want to be sure not to have interactive input
* good idea, I can implement also a "show current otp and next one"

**Comment by paolostivanin** [comment]
I'm still not sure whether I should develop a feature complete CLI version or not :thinking: 
If I do that, for every thing I do for the GUI version I'd have to do it also for the CLI version. This means double work, double maintenance because not all the code can be reused, unfortunately.
What is your exact use case for the CLI @tentator ? A 1 to 1 copy of the GUI version or just a subset would be enough? (e.g. `show` and `list`)

**Comment by tentator** [comment]
I'd say that a functional minimal set is more than enough.. I'd even be satisfied with GUI only import but CLI show. In the end the problem is that there is nothing available elsewhere working from CLI.

On Jul 23, 2019 09:52, Paolo Stivanin <notifications@github.com> wrote:

I'm still not sure whether I should develop a feature complete CLI version or not 🤔
If I do that, for every thing I do for the GUI version I'd have to do it also for the CLI version. This means double work, double maintenance because not all the code can be reused, unfortunately.
What is your exact use case for the CLI @tentator<https://github.com/tentator> ? A 1 to 1 copy of the GUI version or just a subset would be enough? (e.g. show and list)

**Comment by paolostivanin** [comment]
For now I'll implement only `show` and `list` then :+1:

**Comment by tentator** [comment]
It works!! Thank you!!

**Comment by paolostivanin** [comment]
You already compiled and installed it? :D you're fast 🤣 
Glad to hear that it's working 👍

**Comment by tentator** [comment]
you can bet on it.. was long waiting for.. I'm planning to use some ansible magic on top of it, will let you know how it coasts! :)

tent:wq

**Comment by paolostivanin** [comment]
ansible? :D now I'm curios to hear your use case ;)
