### ISSUE TITLE
Package 'jansson', required by 'virtual:world', not found

### ISSUE THREAD

**Issue by andrewmercerCA** [paolostivanin/OTPClient#138]
Successfully built the OTPClient on Fedora 28, but getting this error on my Fedora 29 laptop:

--   Package 'jansson', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:457 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:642 (_pkg_check_modules_internal)
  CMakeLists.txt:38 (pkg_check_modules)

However, I do have jansson installed:

rpm -q jansson
jansson-2.11-2.fc29.x86_64

**Comment by paolostivanin** [comment]
Hello!
Do you have also jansson-devel installed?

**Comment by andrewmercerCA** [comment]
Argh. My apologies, that was it. Thank you!
