### ISSUE TITLE
Add sort feature

### ISSUE THREAD

**Issue by rptx** [paolostivanin/OTPClient#141]
Allow to sort entries by **Issuer**

**Comment by paolostivanin** [comment]
Hello,
this would require some refactoring ([here why](https://github.com/paolostivanin/OTPClient/blob/da88a84f12f4848f47e14b2d5984abdbf751b116/src/treeview.c#L39)), so I will try to implement it for v2.

**Comment by rptx** [comment]
Thanks @paolostivanin.
I will be patient. ;)
Good work, by the way. :+1:

**Comment by paolostivanin** [comment]
thanks :)

**Comment by rptx** [comment]
Hello @paolostivanin ,
Thanks for the implementation of the feature. :)
May i suggest a little improvement? : 
Would it be possible to save the sort order when exiting the application?
This would make it possible to retrieve it the next time you open the application.

**Comment by paolostivanin** [comment]
Hi, sure no problem :)
Could u pls open a new issue so that I can prioritize it?
