### ISSUE TITLE
add support for OTP Auth by Roland Moers

### ISSUE THREAD

**Issue by idnovic** [paolostivanin/OTPClient#147]
On iOS you would use OTP Auth. https://cooperrs.de/otpauth.html

Please add support for the file format. I did like to be able to import/export between OTPClient and OTP Auth.

I attached an exported encrypted file from OTP Auth.

Password is 1111
You can expect to find 1 entry named Test.

The file format is documented here: https://github.com/CooperRS/decrypt-otpauth-files

[OTPAuth.zip](https://github.com/paolostivanin/OTPClient/files/3338936/OTPAuth.zip)

**Comment by paolostivanin** [comment]
I'm sorry but I don't think this will ever be implemented. I don't have an iOS device with which I could test this feature and, furthermore, implementing it would require quite some work because it uses rncryptor, a completely different data model.
