### ISSUE TITLE
Add new item using a QR image from clipboard directly

### ISSUE THREAD

**Issue by yshalsager** [paolostivanin/OTPClient#148]
I think this would be a nice feature to be added to the current new items methods.
Thanks for making this awesome app!

**Comment by paolostivanin** [comment]
I'll add it to v2.0 :+1:  thanks for your suggestion!

**Comment by yshalsager** [comment]
@paolostivanin Thanks for your awesome work, really appreciate it.

**Comment by paolostivanin** [comment]
@yshalsager just understand your requirement: do you mean parsing an encoded image from clipboard (base64 maybe?) OR parsing the file path given by the clipboard when an image is copied?

i.e. if I copy an image in GNOME, then I get the following when pasting the data:
```
file:///home/pstivanin/Downloads/test.png 
```

**Comment by yshalsager** [comment]
@paolostivanin I mean getting a copied image from the clipboard and add an entry of that image QR.

**Comment by huyizheng** [comment]
The latest v2.0-dev branch got `(1.99.0:10657): Gtk-WARNING **: 15:47:57.009: Child name 'import_qr_menu' not found in GtkStack` error when tried to import config from qr code.

**Comment by huyizheng** [comment]
> @yshalsager just understand your requirement: do you mean parsing an encoded image from clipboard (base64 maybe?) OR parsing the file path given by the clipboard when an image is copied?
> 
> i.e. if I copy an image in GNOME, then I get the following when pasting the data:
> 
> ```
> file:///home/pstivanin/Downloads/test.png 
> ```

I think that add the first feature you mentioned is also useful, especially for non-gnome users.
For example, in KDE, I can't use "import from screenshot", but KDE's screenshot tools provides a "copy to clipboard" function. If the first feature you mentioned is available, then I can add account without saving screenshot file.

**Comment by paolostivanin** [comment]
done with latest commit on `v2.0-dev` branch
