### ISSUE TITLE
Does not show token

### ISSUE THREAD

**Issue by spookylukey** [paolostivanin/OTPClient#149]
When I click on a line, it doesn't show the OTP token (contrary to what is in the wiki). I can't find any way to get it to display the token.

I'm using 1.5.1, installed via Flatpak on Linux Mint 18. I'm guessing this is some kind of packaging issue?

Also, it doesn't copy the token to the clipboard either - at least if I'm running my clipboard manager it doesn't (either to primary or secondary selection). I found that if I close the clipboard manager, it does copy it.

**Comment by paolostivanin** [comment]
Hello,
:thinking: that's interesting. I'll look into it. a couple of questions first:
1) are u using LM 18 cinnamon edition?
2) what do u mean by "my clipboard manager"?

**Comment by spookylukey** [comment]
1. Yes, cinnamon edition
2. I'm running CopyQ to keep clipboard history

**Comment by paolostivanin** [comment]
Hi,
my test setup:
- linux mint 18.3 64bit cinnamon edition
- flatpak from official repo
- otpclient installed from flathub (v1.5.1)
I added a token using the manual method, and the program showed it correctly (and the token was successfully copied to the clipboard).

About using an external clipboard: I'm sorry, I don't really know what to do here. I can't test every clipboard manager out there :) I'll add a warning into the wiki that only the "default" clipboard is supported.

**Comment by paolostivanin** [comment]
I need a working reproducer from you to fix the issue because I can't reproduce it :disappointed:

**Comment by spookylukey** [comment]
Thanks so much for looking into this. I'm afraid I'm unlikely to find the time to get this reproducible, so I think it's best to close the issue. I'm able to use other apps. Thanks for your time!

**Comment by paolostivanin** [comment]
Sorry to hear that :disappointed: 
If you'll ever find a way to reproduce it, please let me know because I never liked bugs :)
