### ISSUE TITLE
[andotp] new encryption algo

### ISSUE THREAD

**Issue by loveJesus** [paolostivanin/OTPClient#150]
Praise the Lord I hope you are doing well above all knowing the goodness of God in Christ Jesus, and thanks for your helpful project. Just reporting that the beta of andOTP is using a new encryption method which is unable to be read by OTPClient at this point, this would be a mix of feature request and bug because andOTP doesn't save in the old format anymore. Thanks for your work on this and God guide us and bless you in Jesus Holy name

**Comment by paolostivanin** [comment]
Thanks a lot for the heads-up, very appreciated! :+1:

**Comment by paolostivanin** [comment]
on hold until https://github.com/andOTP/andOTP/issues/427 is clarified

**Comment by AmarOk1412** [comment]
Arf, just tested to import my andotp archive in OTPClient. I think I need to wait the 2.0.0. Do you know when you want to do a new release?

Have a nice day

**Comment by paolostivanin** [comment]
Hi, I guess that in around a week I'll release it!
