### ISSUE TITLE
[flatpak][solus] can't open file chooser

### ISSUE THREAD

**Issue by augns** [paolostivanin/OTPClient#151]
Hi, really love your app. I'm currently running into a problem in that I can't get the native file chooser to open when I try to import a andOTP backup. I've tried to get some idea in the terminal and the below is what I get:

(OTPClient:3): Gtk-WARNING **: 20:42:53.993: Can't open portal file chooser: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.FileChooser” on object at path /org/freedesktop/portal/desktop

I'm currently running otpclient as a Flatpak app in Solus. Not entirely sure if this is a problem with your app, Flatpak or my system.

Thanks for your time!

**Comment by paolostivanin** [comment]
Hi,
I just installed OTPClient from flathub on both Ubuntu 18.04 and Fedora 31 and everything worked as expected. The file dialog showed up when I tried to import an andOTP backup :thinking:

**Comment by augns** [comment]
> Hi,
> I just installed OTPClient from flathub on both Ubuntu 18.04 and Fedora 31 and everything worked as expected. The file dialog showed up when I tried to import an andOTP backup

My current Flatpak verison in Solus is 1.0.9. Don't know if that helps?

I've tried uninstalling your app, deleted the cached files in .var under /home and then reinstall. Same thing still occurs.

I'll try again later and let you know how it goes.

**Comment by paolostivanin** [comment]
On Ubuntu 18.04 the flatpak version was 1.0.8 and on Fedora 31 it was 1.4.3...

**Comment by paolostivanin** [comment]
I was able to reproduce it on a clean Solus 4.0 Budgie environment, so it must be related to that OS.
I'll try to understand what's wrong there...

**Comment by paolostivanin** [comment]
I found the issue :) you probably didn't install the package `xdg-desktop-portal-gtk` as written here: https://flatpak.org/setup/Solus/

install it, **reboot** the system and then you are good to go :+1:

**Comment by augns** [comment]
Yup, that did it. Strange, previously installing that package wasn't necessary. Anyhow, thanks for troubleshooting and the solution!

**Comment by dnkmmr69420** [comment]
I am getting this exact same error except I am on ublue bazzite nvidia
