### ISSUE TITLE
OTPClient is crashing, trying to allocate a huge memory

### ISSUE THREAD

**Issue by AmarOk1412** [paolostivanin/OTPClient#156]
Hi!

I saw that OTPClient got an update to 2.0

So, I retested to import a fresh otpclient backup (plain and encrypted. ~20 passwords)

And, I think it's a bit broken. When I tried to import the plain text backup, I got a crash and then:

```
 ✘ amarok@tars3  ~  flatpak update com.github.paolostivanin.OTPClient 
Looking for updates…


        ID                                            Arch            Branch          Op          Remote           Download
 1. [✓] org.gnome.Platform                            x86_64          3.34            u           flathub            1.0 kB / 318.5 MB
 2. [✓] org.gnome.Platform.Locale                     x86_64          3.34            u           flathub            1.0 kB / 322.8 MB
 3. [✓] org.freedesktop.Platform.GL.default           x86_64          19.08           u           flathub            1.9 kB / 90.8 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel          x86_64          19.08           u           flathub            1.9 kB / 8.7 MB
 5. [✗] org.freedesktop.Platform.openh264             x86_64          19.08           i           flathub          595.3 kB / 593.4 kB
 6. [✓] com.github.paolostivanin.OTPClient            x86_64          stable          u           flathub          668.0 kB / 1.2 MB

Warning: org.freedesktop.Platform.openh264 not installed
Changes complete.
 amarok@tars3  ~  flatpak run com.github.paolostivanin.OTPClient   
[WARNING] your OS's memlock limit may be too low for you (65536 bytes). Please have a look at https://github.com/paolostivanin/OTPClient#limitations
Error while loading json data: 
Couldn't allocate secure memory
double free or corruption (fasttop)
 ✘ amarok@tars3  ~  flatpak run com.github.paolostivanin.OTPClient
[WARNING] your OS's memlock limit may be too low for you (65536 bytes). Please have a look at https://github.com/paolostivanin/OTPClient#limitations

(2.0.0:2): GLib-ERROR **: 15:52:17.604: ../glib/gmem.c:135: failed to allocate 18446744073709551600 bytes
```

I am on Fedora 31, i3.

If you want me to test or provide more informations, feel free to ping me (for now, I didn't get the time to compile from source in debug mode to give you a backtrace via gdb. I can remove the .enc database or give more infos about that file if necessary.

Have a nice day

**Comment by paolostivanin** [comment]
Hi,
it seems that you don't have enough space for allocating the needed secure memory pool:

```
[WARNING] your OS's memlock limit may be too low for you (65536 bytes). Please have a look at https://github.com/paolostivanin/OTPClient#limitations
Error while loading json data: 
Couldn't allocate secure memory
```
Please try to increase the memlock value as written here (https://github.com/paolostivanin/OTPClient/wiki/Secure-Memory-Limitations) and try again :)

**Comment by AmarOk1412** [comment]
@paolostivanin In fact I already read that page, and it's not the issue here.

The backup I generate is good for andOTP, not for OTPClient. The interesting line in my logs if the allocated size at the end

So, just to test I removed the limitation and I tried again:

̀```
 amarok@tars3  ~  flatpak run com.github.paolostivanin.OTPClient

(2.0.0:2): GLib-ERROR **: 18:33:31.930: ../glib/gmem.c:135: failed to allocate 18446744073709551600 bytes
```

Even if I have a lot of RAM, there is no way I can allocate 18446744073709551600 bytes :)

**Comment by paolostivanin** [comment]
What you are doing is:
1. export encrypted backup from andOTP 0.6.3 or greater which contains ~20 tokens
2. import the encrypted backup to OTPClient 2.0.0
3. crash

right?

**Comment by AmarOk1412** [comment]
In fact, the encrypted backup didn't worked. I tried with the plain text backup

1. Export plain text backup from andOTP 0.6.3.1-play
2. Import with latest flatpak (so I think it's 2.0.0)
3. crash
4. Re-open the flatpak
5. Unlock the db
6. Crash (with that message)

If you need, I can compile OTPClient in debug mode and run it into gdb to get the full backtrace (this will need to wait the week end)

**Comment by paolostivanin** [comment]
Hi! I was able to reproduce the issue with 25 tokens on openSUSE Tumbleweed using flatpak.
Basically, when I tried to import the encrypted backup with a too low memlock value (65535) the app crashed and the db got corrupted.
Starting the app again caused it to crash with the same error you wrote.
So I deleted the corrupted db, set the memlock limit 16384 and rebooted the pc. After that I tried to import the backup again and it worked like a charm.

**Comment by paolostivanin** [comment]
The only thing I can do to avoid this situation in the future is to better warn the user when the value is too low and, of course, to avoid db corruption :/

**Comment by AmarOk1412** [comment]
Ok I didn't delete the corrupted database for the debug.

Will try to do it again

**Comment by AmarOk1412** [comment]
Ok, just removed the app data and tried again. Everything is working, thx for your app :)

**Comment by paolostivanin** [comment]
Nice :D now I'll work on making it more fault tolerant :+1:
