### ISSUE TITLE
Debian package for 2.0/PPA

### ISSUE THREAD

**Issue by SuperSandro2000** [paolostivanin/OTPClient#161]
Is there any particular reason why the ppa does not contain version 2.0? Could this be restored?

**Comment by paolostivanin** [comment]
Hi!
I'm not in charge of the PPA, so I have no idea why it hasn't been updated yet :)
Just email (if possible) the PPA admin!

**Comment by SuperSandro2000** [comment]
I send him an email. If I remember it I will update you on the matter.

**Comment by SuperSandro2000** [comment]
He plans to update it soon. Great to hear that.
