### ISSUE TITLE
Won't install on ARCH

### ISSUE THREAD

**Issue by JustAManWIthAPlan** [paolostivanin/OTPClient#168]
I tried the manual and the AUR way

I get an error with libbaseencode failing to build
I tried installing libbaseencode both through AUR and manually to no avail 

Anyone know how to fix?

**Comment by paolostivanin** [comment]
Hello,
I'll have a look at it. Let me spawn a vm and try!

**Comment by paolostivanin** [comment]
Hello
```
$ yay -S libbaseencode
...
==> Finished making: libbaseencode 1.0.9-2 (Sat 21 Mar 2020 06:49:52 PM CET)
==> Cleaning up...
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) libbaseencode-1.0.9-2

Total Installed Size:  0.02 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                               [################################################################] 100%
(1/1) checking package integrity                                                                             [################################################################] 100%
(1/1) loading package files                                                                                  [################################################################] 100%
(1/1) checking for file conflicts                                                                            [################################################################] 100%
(1/1) checking available disk space                                                                          [################################################################] 100%
:: Processing package changes...
(1/1) installing libbaseencode                                                                               [################################################################] 100%
```
no problem whatsoever installing `libbaseencode`. I used an up-to-date archlinux system.

**Comment by JustAManWIthAPlan** [comment]
Hey there, thanks for the fast response

==> Making package: libbaseencode 1.0.9-2 (Sat 21 Mar 2020 06:57:12 PM CET)
==> Retrieving sources...
  -> Downloading v1.0.9.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   135  100   135    0     0   1483      0 --:--:-- --:--:-- --:--:--  1483
100  9736  100  9736    0     0  25222      0 --:--:-- --:--:-- --:--:-- 25222
  -> Downloading v1.0.9.tar.gz.asc...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   607  100   607    0     0   6457      0 --:--:-- --:--:-- --:--:--  6457
100   833  100   833    0     0   1649      0 --:--:-- --:--:-- --:--:--  7933
==> Validating source files with sha256sums...
    v1.0.9.tar.gz ... Passed
    v1.0.9.tar.gz.asc ... Skipped
==> Verifying source file signatures with gpg...
    v1.0.9.tar.gz ... FAILED (unknown public key 3C9BE9B64EC1EA64)
==> ERROR: One or more PGP signatures could not be verified!
Error downloading sources: libbaseencode

when not importing keys

:: Importing keys with gpg......
gpg: keyserver receive failed: Permission denied
==> Error: Problem importing keys

when importing keys

**Comment by paolostivanin** [comment]
1) is your system up-to-date?
2) could you try to install it using `yay` (https://github.com/Jguer/yay) ?

**Comment by JustAManWIthAPlan** [comment]
1. Yes, updated like 10 minutes ago
2. Tried it with yay, those results were from yay

**Comment by paolostivanin** [comment]
see here: https://github.com/Jguer/yay/issues/656
maybe this can help, especially the last comment :)

**Comment by JustAManWIthAPlan** [comment]
Still the same issue, weird

**Comment by paolostivanin** [comment]
There must be a misconfiguration somewhere, I'm sorry I can't help you more but I can't reproduce the issue in my archlinux box.
The only alternative until you figure it out how to fix this is to use flatpak instead!

**Comment by JustAManWIthAPlan** [comment]
Ye Flatpak installation worked, wish there was a dark mode, but everything works,

**Comment by paolostivanin** [comment]
You'll find it in the next release :)
Thanks for the idea!
