### ISSUE TITLE
add support for system themes

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#169]
Handle system themes

**Comment by JustAManWIthAPlan** [comment]
if i might suggest, add support for system themes :), if not dark mode will do

**Comment by paolostivanin** [comment]
Sounds good :) thanks!

**Comment by paolostivanin** [comment]
What exactly do you mean with "system themes"? AFAIK, the app gets the theme you currently have applied :thinking:

**Comment by JustAManWIthAPlan** [comment]
Yes

**Comment by paolostivanin** [comment]
Sorry, I can't understand. What are u asking here?
If the app already gets the theme you applied on system level, what is it that you'd like to see implemented by otpclient?

**Comment by JustAManWIthAPlan** [comment]
Oh i guess it does that, I'm using i3, so it's just white themed, add a dark mode then :+1:

**Comment by paolostivanin** [comment]
Sorry, I'm only supporting GNOME because, otherwise, it'd be a mess to support all the DEs out there :)
Still, I think you can change the theme of gnome apps in i3 by using `LXAppearance`.
