### ISSUE TITLE
Would like to maintain on arch

### ISSUE THREAD

**Issue by JustAManWIthAPlan** [paolostivanin/OTPClient#170]
As it states on the wiki you are open to people maintaining packages, If you want to talk hit me up on Discord 
Joaquin Phoenix#7289

**Comment by paolostivanin** [comment]
can you please give me your aur username?

**Comment by JustAManWIthAPlan** [comment]
JoaquinPhoenix

btw I'm new to do this stuff :/

**Comment by paolostivanin** [comment]
For maintaining otpclient you have to contact https://aur.archlinux.org/account/KingofToasters and ask him to add you as co-maintainer :)
I suggest you learn how to properly maintain a package before you do though!

Thanks for your help!

**Comment by JustAManWIthAPlan** [comment]
alright
