### ISSUE TITLE
Amazon OTP Codes

### ISSUE THREAD

**Issue by elguaposghost** [paolostivanin/OTPClient#172]
When adding an Amazon account using the QR code and the manual entry, the codes generated do not match what Amazon is expecting. I do not know if Amazon is using a different algorithm not supported by the app.

**Comment by paolostivanin** [comment]
Hi, that's weird. I have a couple of Amazon codes (they were added years ago though).
I'll try again.
BTW, are u talking amazon.com/de/it/etc or AWS?

**Comment by elguaposghost** [comment]
I was using Amazon and not the AWS portal.

Joshua Lawson
+1.980.277.1425 (M)
+1.513.885.8324 (M)

**Comment by paolostivanin** [comment]
I just tried again with my Amazon account and it worked.
I did again the 2-fa procedure and I imported the QR code using OTPClient. The code generated by OTPClient worked fine :thinking:

**Comment by elguaposghost** [comment]
The weird thing is that I scan the QR code using the clipboard and also scan it with another app seconds apart, but within the time frame, and the codes do not match. The code on my iPhone using OTP Auth work, but not OTPClient.

Joshua Lawson
+1.980.277.1425 (M)
+1.513.885.8324 (M)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by paolostivanin** [comment]
Are you on gnome? If so, can you try with "Take screenshot"?

**Comment by elguaposghost** [comment]
I am on XFCE using Xfce4-screenshooter. However, the QR codes using the same screenshot tools work for all other sites. Here is the error I receive with Amazon:

- Open your Authenticator App. [Need an app?](https://www.amazon.com/a/settings/approval/appbackup?ref=ch_adsec_addExtraApp_attempt#)
- Add an account within the app, and scan the barcode below.
Removed the QR
-
- [Can't scan the barcode?](https://www.amazon.com/a/settings/approval/appbackup?ref=ch_adsec_addExtraApp_attempt#)
- Enter OTP. After you've scanned the barcode, enter the OTP generated by the app:

Incorrect code. If this error repeats, rescan the barcode.

I am in the US, not that it should make a difference: https://www.amazon.com/a/settings/approval/appbackup?ref=ch_adsec_addExtraApp_attempt

- [Your Account](https://www.amazon.com/gp/css/homepage.html?ref=ch_2sv_breadcrumb_ya)
- ›
- [Login & security](https://www.amazon.com/ap/cnep?clientContext=134-9276145-8215717&openid.assoc_handle=usflex&marketPlaceId=ATVPDKIKX0DER&pageId=usflex&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&siteState=clientContext%3D140-9069249-4733365%2CsourceUrl%3Dhttps%253A%252F%252Fwww.amazon.com%252Fa%252Fsettings%252Fapproval%252Fappbackup%253Fref%253Dch_adsec_addExtraApp_attempt%2Csignature%3DsjxwlLmj2FPqpOH5bk2Qtal1xATI4j3D&ref=ch_2sv_breadcrumb_cas)
- ›
- [Two-Step Verification (2SV) Settings](https://www.amazon.com/a/settings/approval?ref=ch_2sv_breadcrumb_adsec)
- ›
- Two-Step Verification

Joshua Lawson
+1.980.277.1425 (M)
+1.513.885.8324 (M)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by paolostivanin** [comment]
Nah, it shouldn't matter whether you're using amazon.com or .de/it/fr/etc
Can you try to execute otpclient from the terminal and check whether you get something interesting?

**Comment by elguaposghost** [comment]
Ok, I figured something out, but this still does not tell me what happened. The Flatpak is what gives me the issue. When I install from source code, it works as expected.

Joshua Lawson
+1.980.277.1425 (M)
+1.513.885.8324 (M)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by paolostivanin** [comment]
Oh, I see, damn flatpak. I'll have a look at it this weekend

**Comment by paolostivanin** [comment]
I just tried importing an Amazon qrcode using the flatpak version and I had no issues with it.
The code worked fine :confused:

**Comment by elguaposghost** [comment]
I am starting to think my issue may have something to do with time as well. I do not know enough about OTP algorithms, but I suspect the codes not matching may be due to some issue on my system with the time. I will play around. Please go ahead and close the issue because I am certain this is with my system and not your code. Thanks for the replies and support!

**Comment by paolostivanin** [comment]
Hi,
OTP requires the time on your PC to be perfectly in sync with the "real" time.
On Linux, you can achieve that with NTP :) look how to configure it on your distro and then you are good to go 👍

**Comment by elguaposghost** [comment]
I have it configured and the clock time matches the atomic clocks, so I am not sure what is the cause.
