### ISSUE TITLE
Lowercase "totp" type causes OTPClient to not show validity countdown

### ISSUE THREAD

**Issue by alanorth** [paolostivanin/OTPClient#173]
I'm trying to import some TOTP codes from the [Aegis](https://github.com/beemdevelopment/Aegis/) Android client¹ and I noticed that if I import the codes with `"type": "totp"` OTPClient 2.2.1 doesn't show the validity countdown.

Take this example TOTP config:

```json
[
   {
      "algorithm" : "SHA1",
      "digits" : 6,
      "issuer" : "",
      "label" : "Alan:alanorth",
      "last_used" : 1588853055570,
      "period" : 30,
      "secret" : "ME3BQTOXQZEP6XRLNNLHUVORQSMA5QRKCL4KVFNK322CW2AX3IE2W7JG",
      "tags" : [],
      "thumbnail" : "Default",
      "type" : "totp",
      "used_frequency" : 0
   }
]
```

If I import this as is, with the lowercase "totp" then OTPClient does not show the validity countdown:

![lowercase-totp-no-validity-countdown-fs8](https://user-images.githubusercontent.com/191754/81387397-46704d00-911f-11ea-9016-d62d2d174934.png)

If I upper case the string to TOTP then OTPClient behaves as expected:

![uppercase-TOTP-validity-countdown-fs8](https://user-images.githubusercontent.com/191754/81387427-5720c300-911f-11ea-983d-b4609502f4cd.png)

I think it was strange so I decided to post it here. Thanks for OTPClient!

--- 
¹ I actually had to write a [Python script](https://gist.github.com/alanorth/9175bf9ff3f483fd7f7187a9187acb77) to convert their plaintext backup JSON format to [andOTP-style JSON](https://github.com/andOTP/andOTP/wiki/Backup-format).

**Comment by paolostivanin** [comment]
Thanks for reporting the issue :)
That's happening because of https://github.com/paolostivanin/OTPClient/blob/51b8341804eb2ee1f73bd9405a044e8755ec2793/src/liststore-misc.c#L53 !

I'm gonna fix it asap and I'm also gonna add support for aegis :)

**Comment by paolostivanin** [comment]
todo:
- [ ] fix this issue
- [ ] add support for Aegis

**Comment by alanorth** [comment]
@paolostivanin that's great, thanks! Aegis seems to be a pretty full-featured, well-written client. I haven't used andOTP in a while so I can't really compare, though I'm impressed they have documented their backup format so well on their wiki.

For what it's worth the super basic Python script I wrote to convert plaintext Aegis JSON backup to plaintext andOTP JSON is here: https://gist.github.com/alanorth/9175bf9ff3f483fd7f7187a9187acb77

**Comment by paolostivanin** [comment]
Thanks Alan :) 
Yes, importing the plaintext backup from aegis seems easy and straightforward to implement, even in C.
Importing the encrypted version though would require way more work, and I don't think I'm gonna invest time into this.

**Comment by alanorth** [comment]
Maybe someone from the Aegis team would be interested. Or at least we could
encourage them to document their backup format better. For now a plaintext
backup is enough for me!

**Comment by paolostivanin** [comment]
do you by change have a steam account in your aegis backup? If yes, could you please paste here the snippet (with the sensible data scrambled out, oc)

**Comment by alanorth** [comment]
> do you by chance have a steam account in your aegis backup?

Nah I don't use Steam. :\ Looks like I can close this issue though. Cheers!
