### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by bertob** [paolostivanin/OTPClient#175]
The current icon isn't too terrible, but it looks a bit "light" with the thin strokes and no fill. It also doesn't really follow the icon guidelines so it doesn't fit in with other apps very well.

Would you be interested in a new icon? If so, I'd be happy to help with that.

**Comment by paolostivanin** [comment]
Hello!
I'd be more than interested in a new icon :sunglasses: 
I have 0 skills in design & draw, that's why I've never invested time into this :smile:

**Comment by bertob** [comment]
Cool, I'll try some things and get back to you when I have something :)

**Comment by bertob** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/1908896/84142627-687a2980-aa55-11ea-97a7-c3a49ba5739d.png)

**Comment by paolostivanin** [comment]
I really like it :) that's really cool man!!! :1st_place_medal:

**Comment by bertob** [comment]
Great! I tweaked the lock a bit to make it look larger, and added a symbolic:

![image](https://user-images.githubusercontent.com/1908896/84186296-9f216580-aa90-11ea-96e3-f6e7bfae9614.png)

If this is fine with you I can do a PR which adds the files to the icons directory.

**Comment by paolostivanin** [comment]
super cool :)
Yes, please, open a PR once you're ready :sunglasses: 
And thanks a lot again, very appreciated!

**Comment by paolostivanin** [comment]
Thanks again :+1: :D
