### ISSUE TITLE
Improve setup flow

### ISSUE THREAD

**Issue by amo13** [paolostivanin/OTPClient#176]
Just a small idea for a better setup flow
I just tried to setup otpclient with my andotp encrypted backup but did not remember the decryption password for my backup so, I hit cancel. I wanted to try on another backup file encrypted with another password but when opening otpclient again, it just asks me the password for the first selected file again. No possibility to select another file. So I removed the first backup which I failed to decrypt and restarted optclient, but now it wants to create a new database instead of letting me choose a backup file...

**Comment by paolostivanin** [comment]
I'll look into that, thanks for reporting this :+1:

**Comment by amo13** [comment]
Where is this "memory" of the last selected file for backup import or even the first run of the app stored? I couldn't find any config file (archlinux). Uninstalling and reinstalling the package did not reset the settings

**Comment by paolostivanin** [comment]
It's located in `$HOME/.config/otpclient.cfg`

**Comment by paolostivanin** [comment]
#199 is part of this
