### ISSUE TITLE
Importing from encrypted antOTP backup only works with legacy exports

### ISSUE THREAD

**Issue by amo13** [paolostivanin/OTPClient#177]
With andOTP 0.6.3 the encrypted backup export changed. Importing from encrypted backups created with 0.6.3 or newer is not working.

**Comment by paolostivanin** [comment]
That's weird because OTPClient supports only the new andOTP encryption format.
I just tried exporting and importing my encrypted andOTP backup and it works fine (I'm using 0.7-beta)

**Comment by amo13** [comment]
Oh, then I might have done some mistake... I also tried exporting a fresh encrypted backup and then importing it failed saying that either the password is wrong (it was not, I just made then backup seconds before) or the file is corrupt.
I just assumed it was still on the old format from andotp, sorry

Any idea how I could troubleshoot?

**Comment by paolostivanin** [comment]
1. how long is the password?
2. try to run otpclient from terminal `otpclient` , what do you get?

**Comment by amo13** [comment]
Ok, so I delete my ~/.config/otpclient.cfg and run `otpclient` from a terminal window.
On the first dialog window, I select "Restore existing database", select the andOTP encrypted backup I just created with a 8 characters password containing lower case letters, upper case letters, digits and an exclamation mark. After typing in the password, it says "Either the file is corrupted or the password is wrong". Optclient does not output anything to the terminal window.

**Comment by paolostivanin** [comment]
I see! What version are u using? In v2.2.0 I've improved the wording of the first dialog setup, so now it's showing _"Restore existing OTPClient database"_.
This means that you can restore an existing **otpclient** backup, and not a 3rd party backup :+1:

**Comment by amo13** [comment]
Oh no..... I could have guessed that. Thank you a lot for making that clear!
And thank you for this application in the first place :)
