### ISSUE TITLE
Entries get duplicated and/or code is wrong when view is sorted

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#184]
When column is sorted, some entries get duplicated.
This seems to be an issue with GtkTreeView itself, so I need to add some kind of workaround.

For now, resetting the sorting order fixes the issue.

**Comment by paolostivanin** [comment]
evaluate https://developer.gnome.org/gtk4/stable/ListContainers.html#id-1.4.5.2.11

**Comment by paolostivanin** [comment]
or this https://developer.gnome.org/gtk4/stable/GtkListBox.html

**Comment by FranciscoPombal** [comment]
Can confirm. This is the most serious and annoying bug right now IMO. Other than that, this is a great piece of software.

**Comment by paolostivanin** [comment]
I agree, that's super annoying. And, unfortunately, the only thing I can do is to migrate away from GtkTreeView...

**Comment by FranciscoPombal** [comment]
I guess this is the related upstream bug: https://gitlab.gnome.org/GNOME/gtk/-/issues/2892.

Unfortunately, it is closed now. But judging from the only response it received, it seems like they missed the point a bit. I think it would be worth re-submitting or reopening, perhaps with a GIF showing it happening on OTPClient.

Also, I should clarify that in my case, I don't think I've ever experienced the "duplication" - just the wrong 2FA code being displayed in the wrong row.

**Comment by paolostivanin** [comment]
If you execute `gtk3-demo`, go to Tree View, then List Sore, hit run and reorder the _spinning_ column, you'll see some weird behavior there.
There's actually no point in opening another bug report, because the GNOME team wants to eventually deprecate treeview. So better to migrate away from it asap :)

**Comment by forerser** [comment]
> When column is sorted, some entries get duplicated.
> This seems to be an issue with GtkTreeView itself, so I need to add some kind of workaround.
> 
> For now, resetting the sorting order fixes the issue.

how to reset sorting order??

Today no one code works, but yesterday everything worked fine

**Comment by paolostivanin** [comment]
That's weird, sorting has been disabled on 2.4.4, so this shouldn't be an issue anymore.
Have you checked if your system clock is in sync with the real time?

**Comment by forerser** [comment]
the error was exactly the system clock.

**Comment by paolostivanin** [comment]
- [ ] implement rows drag and drop
  - [x] set treeview reordable
  - [ ] update the database with the new order
- [ ] test code
  - [ ] reorder and exit app
  - [ ] remove an otp and check that it still works fine
  - [ ] shows one or more otp, reorder the rows, exit the app
