### ISSUE TITLE
Move away from gnome-shell screenshot API

### ISSUE THREAD

**Issue by ciciolina** [paolostivanin/OTPClient#185]
Currently, the only supported platform with the QR scanner is GNOME, can you add a setting option or embedded to support more screenshot app's? like flameshot, Shutter or other alternatives. This will allow us to get more support and cover more DE for all users that have others DE different or non compatible with gnome.

This is the error we get on a non-gnome desktop environment:

GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: the name org.gnome.Shell.Screenshot was not provided by any .service files

Pd. i have gnome gnome-screenshot working in my system but i dont have gnome-shell, the app call this shell to let me take a QR screenshot, its impossible to me (and others users), install this shell without killing the DE.

System info:
 OS: Arch Linux x86_64 
 Kernel: 5.7.12-arch1-1 
 DE: Cinnamon

Your app its amazing!
Thanks!

**Comment by paolostivanin** [comment]
Hi,
I'll look into it, sure! It will take me some time though, because I have to install VMs, DEs, etc :smile:

**Comment by paolostivanin** [comment]
Investigate https://github.com/flameshot-org/flameshot/blob/dea3c7bb87dd6b8287371548fb17268bbc626843/data/dbus/org.flameshot.Flameshot.xml#L14

**Comment by ciciolina** [comment]
Thanks i wait for future updates, many thanks for your time into this... if you have any instruction or something i can try only say me, kisses!

Pd. I change my DM to XFCE and send same error... on Gnome works perfectly.

**Comment by MrMikeJJ** [comment]
> Ps. I change my DM to XFCE and send same error... on Gnome works perfectly.

I Googled this yesterday. it looks like you mentioned the reason in your first post. Gnome Shell is the dependacy which needs to be installing or to be running (not sure which).

**Comment by paolostivanin** [comment]
The current implementation requires gnome-shell to be running because it uses its dbus api.
With v3 I'll add support for another other 3rd party tool (not sure which one ATM)

**Comment by paolostivanin** [comment]
This is now more important than ever because starting from GNOME 41 this dbus interface will no longer be accessible by third party apps.

**Comment by paolostivanin** [comment]
falmeshot removed most of its dbus api, so it's no longer an option. Need to find a valid and stable alternative.

**Comment by paolostivanin** [comment]
It seems that there's no shared standard to take screenshots across DE. People are working on some kind of screenshot portal, but it's not here yet.
I guess I will simply remove this feature from OTPClient, since there is no real alternative ATM.

**Comment by paolostivanin** [comment]
The screenshot feature will be removed until a stable and cross DE solution will come out.
