### ISSUE TITLE
 Allow to select existing database

### ISSUE THREAD

**Issue by kaipee** [paolostivanin/OTPClient#186]
Similar to Issue #164 , except provide the option to allow selecting a database even after creating or importing one (not only upon first use).

For example, I would like to maintain 2x database files:
 1x for work/corporate 2FA
 1x for private/personal 2FA

At the minute there seems no way to choose which database to use.

**Comment by paolostivanin** [comment]
Good point :) I'll work on that, thanks for reporting this!
