### ISSUE TITLE
Feature Request: Export from CLI

### ISSUE THREAD

**Issue by Spectre5** [paolostivanin/OTPClient#187]
Would it be possible to add a export feature that can be called from the CLI?  I'd like to make automatic backups of my OTP codes to an encrypted directory as part of a broader backup script I use for myself.  Ideally I could make an otpclient backup integrated so that I don't have to manually export the file.  I'd like to run the command in a bash script and then be prompted from my password before exporting (to Aegis JSON, for my use case).

**Comment by paolostivanin** [comment]
Good idea, I'll add it to the list :)

**Comment by Spectre5** [comment]
I'm sure this isn't really high priority, but any idea when this might be implemented (so when version 3.0.0 would release)?

**Comment by paolostivanin** [comment]
Hello!
This should be rather easy to implement, so I'm gonna release a v2.4.0 with just this one fixed :+1: 
Theoretically, I should have some free time this week, so it's very likely I'll be able to release it in the next 7/10 days!
About v3.0: https://github.com/paolostivanin/OTPClient/wiki/Roadmap

**Comment by Spectre5** [comment]
That would be awesome - I'll keep my eye out for 2.4.0, thanks!

**Comment by paolostivanin** [comment]
If you want, you can test branch `fix-187` :)
If you do, please let me know how it goes for you!

**Comment by Spectre5** [comment]
That branch doesn't exist :)  But I see a 2.4.0 tag plus it is in master.  I tested it out and it seems to work, so that's great.  But I have another request for this, which I'll open as a new issue!

**Comment by paolostivanin** [comment]
Cool, thanks for double checking!
