### ISSUE TITLE
[feature request] pass the db password via a cmdline param (or read from the system keyring)

### ISSUE THREAD

**Issue by eadmaster** [paolostivanin/OTPClient#189]
i'd like to unlock my db using the kdewallet

**Comment by paolostivanin** [comment]
Hello,
as this is something I don't use (and have no knowledge of), I'll leave this open in case any contributor would like to help.

Cheers

**Comment by eadmaster** [comment]
no problem, i've made a wrapper for `otpclient-cli` using `kwallet-query` + [this expect script](https://stackoverflow.com/questions/12202587/automatically-enter-ssh-password-with-script#answer-28293101).

The GNOME equivalent of KDE Wallet is the GNOME Keyring, but unfortunately they are not compatible atm.

**Comment by paolostivanin** [comment]
GNOME keyring is not supported either. I may look into it into the future, but not sure ATM.

**Comment by brianjmurrell** [comment]
Having to unlock on each use is annoying.  That doesn't mean it has to be unlocked though.  GNOME Keyring could be used as it is unlocked using the login/screensaver entered password.

**Comment by paolostivanin** [comment]
It's on my "things for the future" list :) I'm currently busy with the GTK4 port and UI overhaul, and until that big of a task is done I won't have time to look into anything else!

**Comment by paolostivanin** [comment]
- [ ] use libsecret to store the password after first unlock
- [ ] config option to allow user to disable this feature

**Comment by pm-pm** [comment]
I have seen this issue beause mentioned during release of version 2.6.0
Pipeping the password, at least to cmd version, is possible with small modification of cli/main.c
