### ISSUE TITLE
Import from Aegis and the generated OTP is invalid

### ISSUE THREAD

**Issue by nalakawula** [paolostivanin/OTPClient#190]
Great app beacuse support import from Aegis json. But, the imported otp is not usable.

I try to login to some account, copy otp from your app, the otp is invalid. When i copy otp from aegis, it's valid.

Thanks

**Comment by paolostivanin** [comment]
Thanks, I'll look into it!

**Comment by paolostivanin** [comment]
One thing: is your clock correctly set? (PS you should use NTP if on Linux)

**Comment by Spectre5** [comment]
@nalakawula did you sort them before you tried selected a code?  Perhaps you were hit with the #181 bug, I was too.  Don't sort the columns and the codes should be good (or update to the newest version if/when it is out).

**Comment by paolostivanin** [comment]
Good point, thanks @Spectre5 :)

**Comment by nalakawula** [comment]
Hi guys,
> One thing: is your clock correctly set? (PS you should use NTP if on Linux)
Yes, of course. My clock is correcly set


I already remove otpclient from my machine. I will reinstall now then try @Spectre5 suggestion . Btw I use flatpak.

Thanks

**Comment by nalakawula** [comment]
Confirmed, Reset column sorting fix my otp problem.
I use OPTClient 2.3.0 from flatpak.

**Comment by paolostivanin** [comment]
Unfortunately, this is due to #184 . Even though you are not experiencing the same issue described there, it's a bug within the GtkTreeView widget.
I still have to find a way around that one :(
