### ISSUE TITLE
[feature request] Export from cli to a specific directory

### ISSUE THREAD

**Issue by Spectre5** [paolostivanin/OTPClient#193]
This is a follow-up to #187.  I've tested the new export from cli functionality and it works, which is great.  I've used it as:

`otpclient-cli export -t aegis`

And this saves the file to my home directory.  I'd like to request 1 more option, an output directory of where to store the file.  Perhaps something like

`otpclient-cli export -t aegis -d ~/backups/otpcodes/`

And then the json file would be written to this specific location instead of the users home directory.  As an alternative, if doing this isn't super straight-forward, then maybe at least an option to output the file to the current directory instead of the home directory.  Then at least a backup script could `cd` to the desired directory and export it there.

**Comment by paolostivanin** [comment]
Hello, 
That'd make perfectly sense! Thanks for reporting it.
I'll release a v2.4.1 and consider this a bug ;)

Happy New year!

**Comment by paolostivanin** [comment]
v2.4.1 is out, enjoy :)

**Comment by Spectre5** [comment]
Awesome, works, thanks much!
