### ISSUE TITLE
App icon has opaque white background

### ISSUE THREAD

**Issue by bertob** [paolostivanin/OTPClient#195]
In GNOME Shell it looks fine:

![image](https://user-images.githubusercontent.com/1908896/103809958-b3473880-505a-11eb-916c-ddeb3a38408e.png)

But on Flathub (and GNOME Software), it seems to have a white background:

![image](https://user-images.githubusercontent.com/1908896/103810038-d40f8e00-505a-11eb-938d-a732e3371505.png)

I had a quick look, and found that the exported PNG assets have a white background. Most likely app stores are picking those up rather than using the SVG.

It's worth noting that most apps do not ship rendered PNG icons these days (they're not really needed for anything), so the easiest fix would probably be to just remove them. Alternatively you could also re-export the assets with a transparent background.

**Comment by paolostivanin** [comment]
Hello! Thanks for reporting this :+1: 
You're saying that I can remove these lines:

https://github.com/paolostivanin/OTPClient/blob/05785ba777dc370fb24b6960a99c6730f36d6e23/CMakeLists.txt#L209-L216

and keep just the svg file in `$DESTDIR/share/icons/hicolor/scalable/apps/` ?

**Comment by bertob** [comment]
>  You're saying that I can remove these lines:

I think so, yes. PNG assets are not needed anymore.

**Comment by paolostivanin** [comment]
I had a look around and it seems you're right! Nowadays only svg files are shipped and installed to `scalable`.

Thanks!
