### ISSUE TITLE
Not possible to change a file to be imported when wrong password given

### ISSUE THREAD

**Issue by michalborek** [paolostivanin/OTPClient#196]
Hi
I found a following bug.

Steps to reproduce:

1. Export encrypted file with andOTP on Android
2. Open OTP Client and choose file to import.
3. Type wrong password

Expected:
When not possible to decrypt (don't know the reason yet, I think the password is valid), I should be able to change the backup file to other file.

Actual:
I still see the prompt to give password without a possibility to choose another file.

**Comment by michalborek** [comment]
The problem was because I tried to import andOtp backup as a new database (my fault), but still lack of changing a decision later is problematic :)

**Comment by paolostivanin** [comment]
That makes perfectly sense 👍 
I'll implement it, thanks for reporting this issue :)

**Comment by decoherencer** [comment]
Is there any chance of temporarily editing or removing any config files for now as a fix to this? 
I can't seem to find any specific file to edit or remove that makes the app behave like a fresh install

**Comment by paolostivanin** [comment]
If installed from distro, the file is located in `$HOME/.config/otpclient.cfg` .
If installed from flatpak, the file is locaed in `$HOME/.var/app/com.github.paolostivanin.OTPClient/data/otpclient.cfg`

**Comment by MadManMoon** [comment]
Hi, what do we do to get around this?

Because I accidentally tried to import an old WinAuth text config that had no password. However, that obviously didn't work, and now it tries to start with that every time. I can't get around it because I can't put no password, and I can't put in a nonsense password.

**Comment by paolostivanin** [comment]
You have to edit the `db_path` value in:

`$HOME/.config/otpclient.cfg ` => if installed from your distro's repos
`$HOME/.var/app/com.github.paolostivanin.OTPClient/data/otpclient.cfg` => if installed from flatpak

**Comment by paolostivanin** [comment]
#176 will be part of this

**Comment by paolostivanin** [comment]
To do:
- [ ] add possibility to change file when setting up for first time via "restore existing"
- [ ] add possibility to change file when importing a third party backup
- [ ] if "cancel" is hit during first setup, do NOT remember the file path
