### ISSUE TITLE
Issuer not properly imported

### ISSUE THREAD

**Issue by michalborek** [paolostivanin/OTPClient#197]
Hello, 
Thank you for maintaining this app! I found additional small issue :)

I use andOTP and it exports the DB in a strange format

`{"secret":"...,"issuer":"Microsoft","label":"michal@...","digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"Microsoft","last_used":123123123,"used_frequency":0,"period":30,"tags":[]}`

But for other keys sometimes it looks like this:

`{"secret":"...,"issuer":"Other Company","label":"Other Company:michal@...","digits":6,"type":"TOTP","algorithm":"SHA1","thumbnail":"Microsoft","last_used":123123123,"used_frequency":0,"period":30,"tags":[]}`

The difference is that in the latter one, there is a label with colon separated issuer and login: `Other Company:michal@...` in addition to issuer field.

It seems that OTPClient reads only the colon separated label, and ignores the issuer field.

I do not know what behaviour is proper here (whether the export of andOTP is inconsistent or OTPClient import does it improperly - unfortunately I do not know that standard).

Anyway I'm letting you know, maybe it's something to fix on your side or maybe on andOTP's :)

I'm OK with closing it as invalid if the problem is on the other side.

**Comment by paolostivanin** [comment]
Thanks for reporting the issue, I'll have a look at it later today :)
