### ISSUE TITLE
OTP cli does not remember the last database

### ISSUE THREAD

**Issue by personaaleatoria** [paolostivanin/OTPClient#199]
After configuring and restarting the app. OTP asks to save a new database without remembering the last one used.

If I select the existing database it warns me that doing so would replace it and the content lost.

I still do it, but it asks me for the password. It  unlocks and all the codes are there. So it didn't replace anything or create a new database.

This is a confusing workflow. I wold expect it to remember the last database and ask for the password straightforwardly.

**Comment by paolostivanin** [comment]
Thanks for reporting this! I'll improve the workflow :+1:
