### ISSUE TITLE
Add support for LinOTP

### ISSUE THREAD

**Issue by marliyev** [paolostivanin/OTPClient#200]
Hello,
I have LinOTP server and using app FreeOTP+. I can import export databases from and to between OTPClient and FreeOTP+ but not LinOTP tokens, LinOTP tokens only working on FreeOTP+.

Thank you

**Comment by paolostivanin** [comment]
Hello!
LinOTP is not a supported provider. What format is LinOTP exporting to?
If you can provide me with a sample file, I can add support for it.

Thanks

**Comment by marliyev** [comment]
Hello, am attached token info from server, this is full info about token. also server can export same info to csv and import from oath csv. Hope to get update from flathub :)

thank you.
![Screenshot_20210202_022225](https://user-images.githubusercontent.com/63017170/106525735-e536a800-64fd-11eb-934f-7b499bc8db3c.png)

**Comment by marliyev** [comment]
am also exported this otp from freeotp+, here is example:

otpauth://totp/LinOTP%3ATOTP0005E0F3?secret=JQZLBL5E7TSZEBFFT334IZ7L36QF4D5PHZE6RPOZW367RRK2GUJ2JVD4KDCIM542JCTJJNYWKKXG4O26KLQDLG2EBFSF32FNWL4732I&issuer=LinOTP&algorithm=SHA512&digits=6&period=30

**Comment by paolostivanin** [comment]
Thanks! I will add support for LinOTP in v3.0 (it will take few months to complete this release though) :+1:

**Comment by marliyev** [comment]
Great, thanks

**Comment by paolostivanin** [comment]
Hi,
can you please provide me with an exported csv file from LinOTP?
