### ISSUE TITLE
Google Authenticator Migration URI / QRCode

### ISSUE THREAD

**Issue by alescdb** [paolostivanin/OTPClient#201]
Hi,

It would be nice if we could import Google Authenticate migration QRCode and/or Uri directly into OTPClient.
Format looks like this :
```
otpauth-migration://offline?data=CjEKCkhlbGxvId6tvu8SGEV4YW1wbGU6YWxpY2VAZ29vZ2xlLmNvbRoHRXhhbXBsZTAC
```
Right now I'm using https://github.com/dim13/otpauth for this purpose.

Thanks & nice project :-)

**Comment by paolostivanin** [comment]
Hello,
thanks, really appreciated.

Sure, no problem. I must warn you though, that new features are all scheduled for v3, so you won't see this happening any time soon (with some luck maybe around May) :)

**Comment by paolostivanin** [comment]
https://github.com/protobuf-c/protobuf-c
