### ISSUE TITLE
get-builder.c hard-codes paths to system paths

### ISSUE THREAD

**Issue by sassy-crick** [paolostivanin/OTPClient#203]
In `get-builder.c` the path to otpclient.ui are hard-coded to `/usr/share` and `/usr/local/share` which does not honor XDG_DATA_DIRS. As a result, the attempt to build the software with EasyBuild will not work, as the `otpclient.ui` will not be found at runtime. 
The same is true if somebody installs the software elsewhere. It would be better to honor XDG_DATA_DIRS.
This could be achieved for example from here:
https://github.com/Jorengarenar/libXDGdirs
Thanks!

**Comment by paolostivanin** [comment]
Thanks, that's a good point.
It should actually be set to `-DCMAKE_INSTALL_PREFIX` :thinking:

**Comment by sassy-crick** [comment]
Thanks for looking into that. My understanding is it also should pick up the XDG_DATA_DIRS environment variable as well, in case it cannot find it where it is expecting it. I am, however, not the expert here so I might be wrong. :smile:

**Comment by paolostivanin** [comment]
Using `-DCMAKE_INSTALL_PREFIX` is enough because  if the file is not found at runtime, it means that something bad happened to the OS :)
