### ISSUE TITLE
Wrong icon in taskbar

### ISSUE THREAD

**Issue by geekley** [paolostivanin/OTPClient#204]
The app (at least flatpak version) is not showing the correct icon in taskbar. Instead, it shows the generic "X" icon.

Version: 2.4.2 flathub
OS: Kubuntu 20.04 amd64
DE: KDE Plasma 5.18.5

Likely the problem is related to the window not having a proper class. It seems to be the app version (2.4.2) instead of the app name (OTPClient). Maybe this line has to do with it?
https://github.com/paolostivanin/OTPClient/blob/712a83e29f011b37ce0131bf453dddc370e22588/src/main.c#L11

Maybe it should be `PROJECT_NAME`? And the .desktop file would need to match the appropriate window class using `StartupWMClass`, I think. For example, something like this:

```desktop
[Desktop Entry]
Type=Application
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=otpclient com.github.paolostivanin.OTPClient
Icon=com.github.paolostivanin.OTPClient
Keywords=OTP;TOTP;HOTP;2FA;Multi-factor Authentication;
Terminal=false
Name=OTPClient
GenericName=Authenticator
Comment=GTK+ TOTP and HOTP client for 2-factor authentication
Categories=GTK;GNOME;Utility;
StartupWMClass=OTPClient
```

**Comment by paolostivanin** [comment]
Hello,
thanks for reporting this!
Good catch, actually `g_set_prgname` is redundant and not needed, because the name is set by `g_application_set_name`.

I'll fix this, update the desktop file and try it on a vm!
