### ISSUE TITLE
Is there a chance for this to be built on windows?

### ISSUE THREAD

**Issue by lemmy04** [paolostivanin/OTPClient#209]
...i mean, there's a windows package the The Gimp, maybe this could work too?

**Comment by paolostivanin** [comment]
Hello,
no, sorry! This program uses Linux features that are not available on Windows.
Also, I don't really have enough free time to investigate or support a system I don't use, sorry!

**Comment by lemmy04** [comment]
let me guess: the secure memory, right?

**Comment by paolostivanin** [comment]
secure memory and screenshot features for sure. Dunno what the status of libzip and libjansson is on Windows. Dunno how well GTK4 plays on Windows (don't think there's even an installer for it)
