### ISSUE TITLE
org.gnome.Shell.Screenshot was not provided

### ISSUE THREAD

**Issue by volker-raschek** [paolostivanin/OTPClient#211]
Hi, 
I receive the following error, when I want to take a screenshot from a QR-Code. Can anyone tell me how to solve the problem, if the intervention by me is necessary?

![Bildschirmfoto vom 2021-05-28 19-29-26](https://user-images.githubusercontent.com/18311012/120021271-21c96a80-bfeb-11eb-80a3-c97048ee2d5d.png)

I installed OTPClient via AUR: https://aur.archlinux.org/packages/otpclient/ 
Here are some more informations: 

![Bildschirmfoto vom 2021-05-28 19-31-46](https://user-images.githubusercontent.com/18311012/120021429-59381700-bfeb-11eb-824d-3608e0ee1188.png)

**Comment by paolostivanin** [comment]
Are you using gnome-shell? The screenshot functionality currently requires gnome-shell

**Comment by volker-raschek** [comment]
> Are you using gnome-shell? The screenshot functionality currently requires gnome-shell

No, I don't have installed gnome-shell. I installed cinnamon-screensaver for the screenshot functionality. 

https://archlinux.org/packages/community/x86_64/cinnamon-screensaver/

**Comment by volker-raschek** [comment]
No that's the problem. It does not work with the cinnamon-screensaver as expected when I want to take a screenshot from a barcode.

**Comment by paolostivanin** [comment]
Ah ok, that makes more sense. The screenshot functionality requires gnome-shell, I'll add a better error message

**Comment by volker-raschek** [comment]
Of course it would be great to support the cinnamon-screensaver. If not, then please notify the maintainer of the AUR package of the OTPClient to add gnome-shell as a dependency.

**Comment by paolostivanin** [comment]
Supporting `cinnamon-screensaver` would help only cinnamon users, I need to add a DE agnostic tool. It's part of #185 
Also, `gnome-shell` shouldn't be a hard dep because there are other ways to add a token. I don't think other users would like to install the whole gnome when they can simply use the other methods :)

**Comment by NewcomerQi** [comment]
Hi, were you able to solve this issue? I had the same problem.

**Comment by paolostivanin** [comment]
What version of OTPClient are you using?
This feature has been removed with version 2.5.0 due to https://github.com/paolostivanin/OTPClient/issues/231#issuecomment-980004970
