### ISSUE TITLE
Allow to paste secret for new token containing white space chars

### ISSUE THREAD

**Issue by ralhei** [paolostivanin/OTPClient#212]
On most websites the secret is bundled into groups for 4 chars, with groups being separated by white space for better readability.

Example:
```
41BY CXP4 3ZPN NULL UX6P SOZU 5H7J JZ54
```
Unfortunately these cannot be pasted directly, they have always to be edited manually, removing white spaces.
It would be really great if your parser would just accept theses codes incl. white space.

**Comment by paolostivanin** [comment]
Good point! I'll add this to v3 :+1:
