### ISSUE TITLE
Accept qr codes for new token in SVG format

### ISSUE THREAD

**Issue by ralhei** [paolostivanin/OTPClient#213]
Websites like atlassian (e.g. for trello) show their barcode in SVG format. 
Copying such a barcode to the clipboard is possible, but the OTPclient doesn't seem to accept it.
When trying to import such an image from the clipboard the OTPclient shows a message about KDE for a very short time, explaining something, but it is too short to be readable.

**Comment by paolostivanin** [comment]
Can you please provide an example file? Thanks!

**Comment by ralhei** [comment]
Hmm, not so easy. I went back to the same site, but it is providing me only my productive code as QR - not something I'd like to share ;-)
And I myself are not really able to reproduce such a code from scratch. So the only options I can think of for now are:
- we put this issue on hold, or close it
- you get yourself a free account on bitbucket.org and enable 2FA there - then you would see the culprit.
Sorry that I cannot provide better support for this issue.
In the moment I circumtvent this problem by registering this SVG barcode on my mobile app, then then putting the QR code shown on my mobile app in front of the camera of my laptop.

**Comment by paolostivanin** [comment]
Ok, I'll create a test account and check then! Thanks for reporting this!

**Comment by ralhei** [comment]
Cool, thanks for having a look at it. Although I must admit this is not of such high priority, but would be very nice if it functions... . Great tool, btw, I really like it.

**Comment by paolostivanin** [comment]
- [ ] add support for SVG
- [ ] add support for JPEG

**Comment by ralhei** [comment]
Very cool - thanks a lot for adding this feature.

**Comment by paolostivanin** [comment]
you're welcome! Sorry it took such a long time though :)
