### ISSUE TITLE
Allow to import encrypted aegis database backup

### ISSUE THREAD

**Issue by ralhei** [paolostivanin/OTPClient#214]
The database backup from aegis is written as a JSON file, containing encrypted entries for the tokens. Since aegis allows encrypted backups only (which totally makes sense), it would be cool if one could import them into OTPclient providing the secret key used in aegis.

**Comment by paolostivanin** [comment]
I'll look into this :)

**Comment by paolostivanin** [comment]
- [ ] import encrypted json
- [ ] export encrypted json
