### ISSUE TITLE
Generate new code on CTRL+C and then copy

### ISSUE THREAD

**Issue by CodingSpiderFox** [paolostivanin/OTPClient#215]
When just selecting an entry with arrow key and pressing CTRL+C, then pasting into the OTP form field on a web page it pasted my password that was still in clipboard

Reason was that OTPClient didn't generate a token when I was pressing CTRL+C

**Comment by paolostivanin** [comment]
Hi,
this can be achieved by pressing `Enter` on the selected row :)
