### ISSUE TITLE
sha512 secret with 104 characters

### ISSUE THREAD

**Issue by michi-zuri** [paolostivanin/OTPClient#216]
Hi I have a TOTP (sha512, 6 digits, 30 seconds) that I'd like to add with a secret that is 104 characters long, but the text entry field only allows 96 characters. Could this be fixed?

**Comment by paolostivanin** [comment]
You mean that if you do:
`+` -> `Manually` -> `Secret` only lets you input 96 chars?

**Comment by paolostivanin** [comment]
I just tried with a 128 chars secret, and it worked fine. The limit is 255 chars.
Are you running on the latest version (`2.4.4`)?

**Comment by michi-zuri** [comment]
2.4.2 from Solus OS repo

> You mean that if you do:
> + -> Manually -> Secret entry only lets you input 96 chars?

yes, the text entry field doesn't allow > 96 chars
I could work around this by exporting my db to aegis, adding the missing letters from the secret in the json and reimporting. First time I pasted from the clipboard and it got silently cropped.

**Comment by paolostivanin** [comment]
This was fixed with release `2.4.3`, so you've gotta update the package on your distro to the latest version :)
