### ISSUE TITLE
FYI: OTPClient is now available in NixOS unstable

### ISSUE THREAD

**Issue by alexbakker** [paolostivanin/OTPClient#217]
As I don't have permission to [edit the wiki](https://github.com/paolostivanin/OTPClient/wiki/Tested-OS-&-Packages), I just wanted to drop by and let you know that OTPClient is now packaged and available in NixOS unstable: https://search.nixos.org/packages?channel=unstable&show=otpclient&from=0&size=50&sort=relevance&query=otpclient. The next stable release (NixOS 21.11) will have it as well.

**Comment by paolostivanin** [comment]
Hello!
Yes, sorry! The wiki is not editable because in the past a spammer started creating pages and editing existing ones. I had to make it read-only :(
BTW, thanks a lot, that's very good news! I've already updated the wiki page!!
