### ISSUE TITLE
Broken link in "Steam Support" wiki page

### ISSUE THREAD

**Issue by Arnavion** [paolostivanin/OTPClient#219]
>I fully support and quote the author of andOTP, so I'm just going to leave the link here for more details: https://github.com/andOTP/andOTP/wiki/Special-features#steamguard-codes

The content is currently at https://github.com/andOTP/andOTP/wiki/Shared-secrets#steam

**Comment by paolostivanin** [comment]
thanks a lot, I've fixed the link :)
