### ISSUE TITLE
is import a merge or overwrite operation?

### ISSUE THREAD

**Issue by brianjmurrell** [paolostivanin/OTPClient#220]
If I want to be able to use a token on multiple machines, can I export my DB from one machine and import it on another and have the import only add new tokens without wiping out any existing tokens?  That is, is import a _merge_ operation?

Even if so, is there any opportunity/situation at all for import to overwrite an existing token with a new different token for a given website?

**Comment by paolostivanin** [comment]
Hello!
Import is a _merge_ operation. For each token found when importing the data, the program compute an hash and check whether the computed hash is identical to one of the entry in the db. If not, the item is added.
Import should never overwrite an existing token (if it did that, it would be a bug)
