### ISSUE TITLE
Not showing OTP value for some rows

### ISSUE THREAD

**Issue by brianjmurrell** [paolostivanin/OTPClient#228]
I have added several rows to my 2.3.2 running OTPClient via QR code and my computer's web-cam.

Some of them show an _OTP Value_ and _Validity_ count down when I click on their row however some don't show any value or any countdown when clicked on.

Any ideas why?

**Comment by paolostivanin** [comment]
Hello,
you should update to the latest version, there has been lots of bug fixes since 2.3.2 :)
No idea what the issue could be. I would need a reproducer in order to debug this.

Can you provide me with some fake qrcode that triggers this issue?

Thanks

**Comment by brianjmurrell** [comment]
I am now running 2.4.7 and the behaviour has not changed.  The one thing I am noticing is that when I click one of the rows that does not display a value stderr reports:

```
(otpclient:2371426): Gtk-CRITICAL **: 14:13:42.561: gtk_clipboard_set_text: assertion 'text != NULL' failed
```

I suspect however that is fallout from a value not being generated.

> Can you provide me with some fake qrcode that triggers this issue?

I have no clue how to do this.

**Comment by brianjmurrell** [comment]
FWIW, these are confirmed working QR codes that I am scanning via webcam from andOTP, which of course work fine in andOTP.

**Comment by paolostivanin** [comment]
Sorry, but without any reproducer I'm not able to work on the issue! I am not facing this issue, and I have dozens of codes.

**Comment by brianjmurrell** [comment]
I know zilch about the technical details of OTP and the QR codes it uses, etc.  Please explain to me how I provide you with a "fake qrcode" (that triggers the issue).

Surely you cannot expect **users** to know this.

**Comment by brianjmurrell** [comment]
Running it in a debugger, `get_totp_at()` is returning `null` and `copt_err` is `INVALID_B32_INPUT`.

**Comment by brianjmurrell** [comment]
With #232, my previously non-working entries are now working.
