### ISSUE TITLE
View camera input during scan from webcam

### ISSUE THREAD

**Issue by brianjmurrell** [paolostivanin/OTPClient#229]
Scanning QR codes from the webcam is a neat feature to be sure.

But when scanning a QR code from the webcam, it would be most helpful if the user could see what the webcam sees, along with a square-box outline of where the app is looking for the QR -- like many QR code scanning apps on phones do.  This would result in less trial-and-error/fumbling-around while blindly waving a camera (or a printout, etc.) in front of the webcam trying to get it in the sweet-spot purely by guessing.

**Comment by paolostivanin** [comment]
Hello,
thanks for reporting this! I'll add it to the list of improvements (as low prio though, so it will take a while to implement it)
