### ISSUE TITLE
Flatpak Version Doesn't Have Option To Restore Existing Database

### ISSUE THREAD

**Issue by Simmonz** [paolostivanin/OTPClient#230]
When using OTPClient from various distros repos when I launch it for the first time I get the option to create a new database or restore and existing one. I don't get this on the Flatpak version that I have to use on a couple systems. I only get the option to create a new one. I can then import my keys over from my main database but the pain is I like to keep one file on my Nextcloud and have every device I have use the same file rather then keep importing keys around. The system in question is using Linux Mint 20.2 and version 2.4.4 of the Flatpak version.

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'll look into it!

**Comment by paolostivanin** [comment]
Hello,
that's because the flatpak version only has access to its data folder, so there's no need for this feature since you wouldn't be able to access files outside the app's data folder.
