### ISSUE TITLE
Issue taking screenshots in Gnome (Fedora 35)

### ISSUE THREAD

**Issue by benji88i** [paolostivanin/OTPClient#231]
Hi there,

This is such an incredible app and it works great. I am not sure why but I am getting this error all of a sudden though.

I have my permissions for screen capture set in Privacy settings,

Can anyone assist

![image](https://user-images.githubusercontent.com/68906758/143476551-1e2f6557-00fc-4b8c-8b65-a07ba148dbba.png)

I am using version 2.4.4

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'll look into it!

**Comment by paolostivanin** [comment]
Unfortunately, GNOME 41 removed other applications access to certain dbus interface, which includes SelectArea: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3943

**Comment by paolostivanin** [comment]
I guess I'll have to remove this functionality...

**Comment by paolostivanin** [comment]
I could use `org.freedesktop.portal.Screenshot` , but it doesn't provide a SelectArea, only a full screen screenshot. 
Honestly, I don't have either the time or the will to chase all GNOME's changes. If no one steps up, I'll remove this feature with the next release, sorry.

**Comment by benji88i** [comment]
Hi there, I know, gnome is doing unnecessary feature updates and user space updates. A rule that Linus torvalds among many others said should never be broken which is don't touch userspace u less it's a functional improvement. There doesn't seem to be a functional improvement. I like it but it has some extensions, tweaks, customisations, and even some apps don't work as the libraries are now removed such as this one with the webcam. 

I am a mechanical engineer with experience in Matlab and I know a bit of language C and maths programming. How could I help? Should I reach out to gnome for help on this?

**Comment by benji88i** [comment]
@paolostivanin 

> Hi there, I know, gnome is doing unnecessary feature updates and user space updates. A rule that Linus torvalds among many others said should never be broken which is don't touch userspace u less it's a functional improvement. There doesn't seem to be a functional improvement. I like it but it has broken some extensions, tweaks, customisations, and even some apps don't work as the libraries are now removed such as this one with the webcam.
> 
> I am a mechanical engineer with experience in Matlab and I know a bit of language C and maths programming. How could I help? Should I reach out to gnome for help on this?

**Comment by paolostivanin** [comment]
Thanks for offering :) the way I see it, GNOME will never fix this because it was marked as security issue. So we have two options:
1. open a feature request for the `org.freedesktop.portal.Screenshot` interface and ask to add the SelectArea method
2. find a good platform-agnostic alternative to this implementation. This would solve also #185

**Comment by paolostivanin** [comment]
I will work on it sooner or later, but don't hold your breath :) 
I'm still slowly going on with the GTK4 port (and not sure whether or not to continue, since I'm fed up with all the changes).

**Comment by benji88i** [comment]
I don't blame you, thanks so so much for all your hard work. Sincerely appreciated  🙂I use this app every single day and I really depends on it. All the other authenticators are very buggy and don't work on fedora your app is the only one that works well.  Do you accept crypto donations?

Also is the project open source perhaps I can contribute? What languages does it run with? 

> I will work on it sooner or later, but don't hold your breath :) I'm still slowly going on with the GTK4 port (and not sure whether or not to continue, since I'm fed up with all the changes).

**Comment by benji88i** [comment]
> Thanks for offering :) the way I see it, GNOME will never fix this because it was marked as security issue. So we have two options:
> 
> 1. open a feature request for the `org.freedesktop.portal.Screenshot` interface and ask to add the SelectArea method
> 2. find a good platform-agnostic alternative to this implementation. This would solve also [Move away from gnome-shell screenshot API #185](https://github.com/paolostivanin/OTPClient/issues/185)

How do I do option 1 , is there a phone number for gnome development team? Should I reach out to them on gihub somewhere, I have close contacts at the fedora community, would that help?

**Comment by paolostivanin** [comment]
> I don't blame you, thanks so so much for all your hard work. Sincerely appreciated slightly_smiling_faceI use this app every single day and I really depends on it. All the other authenticators are very buggy and don't work on fedora your app is the only one that works well. Do you accept crypto donations?
> 
> Also is the project open source perhaps I can contribute? What languages does it run with?
> 

I'm glad to hear that you find my project stable and working well :) 
No, I don't accept any kind of donation, but thanks for asking! Really appreciated!!
The reason is that I just prefer to be "independent" from others' money. If I started accepting donation, then I'd feel like obligated to work on this project. And this is just a side project for me that I work on on my free time, and I want it to stay like this :)

**Comment by paolostivanin** [comment]
> How do I do option 1 , is there a phone number for gnome development team? Should I reach out to them on gihub somewhere, I have close contacts at the fedora community, would that help?
> 
> For option 2, I really love fedora and gnome so much and have used it for many years. I really don't know if I like the way gnome is keeps changing things that don't need to be changed, we need uniformity to keep smart developers like you leaving to build for apple or android or the devil at Microsoft windows sobjoyrofl

For option 1, I think that opening an issue here https://github.com/flatpak/xdg-desktop-portal might be a good starting point. Not sure though.

For option 2, don't worry. I've been using GNU/Linux for years and this is not gonna change any time soon. What I meant with that comment is that if GNOME keeps changing how GTK works, then I'll simply switch to another toolkit (no idea which one though, let's hope it will never come to this) and be done with it.

**Comment by benji88i** [comment]
Sorry for delay,

I have found a great solution to this problem (temporary until gnome allows screen capture again)

What i do is take a screenshot capture of the QR code, then I click "from clipboard" then I click "from file"

and... IT works !!

I will be reaching to the that address first thing tomorrow morning to get this resolved.

Sorry I have a couple of questions as well.

1. Can I ask is there a way to send the backup files to a different location ?

2. Also how do we decrypt the andOTP files

3. Will the other file formats work with Aegis ?

**Comment by paolostivanin** [comment]
I'm glad that you found a suitable workaround :)
About your questions:
1. nope. The user is responsible for taking care of backups. I may improve this area in the future, but for now I have no plans
2. what do you mean by that? andOTP encryption is explained [here](https://github.com/andOTP/andOTP/wiki/Backup-encryption). OTPClient's code about andOTP is [here](https://github.com/paolostivanin/OTPClient/blob/master/src/common/andotp.c)
3. nope, AEGIS is not yet supported. I've planned to add support for it with v2.6.0 (https://github.com/paolostivanin/OTPClient/milestone/17)
