### ISSUE TITLE
Bad UX for deleting keys

### ISSUE THREAD

**Issue by yajo** [paolostivanin/OTPClient#233]
Hi! Thanks for this wonderful app! smiley

I just deleted some keys for the 1st time and found out that the workflow for deleting keys feels like driving without brakes:

    Hit "-"
    Accept dialog with long text.
    Click on row to delete.

If you click on the wrong row for accident, you're doomed.

Example: you follow those steps to delete one item. You don't realize the "-" button is red, and then click on another row because you need that OTP code. bomb boom exploding_head

My proposal:

    Click row.
    Click "-".
    Dialog: "Are you sure you want to delete this item? You won't be able to recover it unless you have another backup!" Buttons: "Delete" (red) and "Cancel"

Simpler and more clear. It'll take more time to delete many items, but at the same time it will feel safe.

---

Original: https://github.com/flathub/com.github.paolostivanin.OTPClient/issues/23

**Comment by paolostivanin** [comment]
thanks for reporting this!
I'll think about it :)

**Comment by idachev-shipcars** [comment]
Just wanted to create the same ticket - but find out that is already commented.

**Comment by paolostivanin** [comment]
Fix will come with 2.6.0 :)
