### ISSUE TITLE
<< Segmentation fault (core dumped) >> when Importing QR as File

### ISSUE THREAD

**Issue by ciro314** [paolostivanin/OTPClient#240]
Hello,

I am running Manjaro, installed OTPClient (2.4.8) from the AUR and imported succesfully some QR codes via '+ >> 'using a QR Code' >> 'Import from file'. When trying to import the QR from a Nextcloud provider, I get the error message << Segmentation fault (core dumped) >>. My Android phone does scan the QR correctly. I tried to import that QR in other machine running Manjaro and got the same error. If this is a bug and I could contribute fixing it, I would help you. Regards

**Comment by paolostivanin** [comment]
Hello,
Seems definitely a bug, even though I don't understand why it's happening only with a particular provider.
Would you be able to generate a fake nextcloud qr code, so that a could debug the issue myself?

Thanks!

**Comment by ciro314** [comment]
![download](https://user-images.githubusercontent.com/39488425/155855090-bf61ed61-1137-4d0a-a15c-06059fae0d0a.png)
Fake QR for Nextcloud

Thank you for answering

**Comment by paolostivanin** [comment]
Thanks, I'll have a look at this asap!

**Comment by paolostivanin** [comment]
Bug confirmed, I think it's an issue with utf8 handling. I hope to have a fix out in few hours. Thanks for reporting this :)

**Comment by paolostivanin** [comment]
the issue is that the separator is `?` instead of `&`: `otpauth://totp/...woelkli.com?secret=...`
Must be something related to nextcloud I guess. Never seen this before.
