### ISSUE TITLE
Question: Any chance to run/compile it on Debian 10 / Buster?

### ISSUE THREAD

**Issue by pm-pm** [paolostivanin/OTPClient#246]
Hello,

i am running Debian 10 Buster.
Compiling is not possible, because "[libcotp-dev](https://packages.debian.org/search?searchon=names&keywords=libcotp)" is not available on Debian 10 Buster.
Is there any chance/binary to run it anyway? _Maybe without so much security?_

pm-pm

**Comment by paolostivanin** [comment]
Hello,
You have to first compile and install https://github.com/paolostivanin/libbaseencode , then compile and install https://github.com/paolostivanin/libcotp and then you can compile and install OTPClient, provided that all other deps are satisfied, of course.

**Comment by pm-pm** [comment]
Hello Paolo.

Brilliant! It works fine.

I must apologise because I did not understand that "cotp" was also yours. I thought this was a native part of debian and only available from version Debian 11.
Maybe you can add a note to the "manual installation of otpclient" that these two libraries are also available on YOUR github.

By the way: Starting the GUI takes about 25 seconds until the password prompt comes up. The CLI works without delay.

Thanks
pm-pm

**Comment by paolostivanin** [comment]
It's actually written here: https://github.com/paolostivanin/OTPClient#manual-installation=
Under the requirements section there's libcotp and a link to the project repo.

That's weird, I've never seen a startup slow-down, not even on small test VMs :thinking:
