### ISSUE TITLE
Sorting doesn't work in Ubuntu 22.04

### ISSUE THREAD

**Issue by philb61** [paolostivanin/OTPClient#247]
According to the wiki:

> It's possible to sort the tokens on the main view by either account or issuer, by just clicking on the relative column headers called "Account" and "Issuer".

At least on Ubuntu 22.04, clicking the column headers does nothing.  I've tried on the distribution packages' 2.4.1, and also compiled 2.5.1 to check.

At least 2.5.1. has a button to "Enable/disable rows reordering", so one can manually change the order.  Has the sorting feature been replaced by this?

**Comment by paolostivanin** [comment]
You're right, I have to update the wiki page. And yes, the sorting feature has been replaced by that button.
