### ISSUE TITLE
Failure importing Authenticator Plus backup

### ISSUE THREAD

**Issue by 3nprob** [paolostivanin/OTPClient#248]
OS: NixOS 21.11 (x86_64, intel)
Version: v2.5.1

First off, attempting to importing the exported file directly fails with
```
An error occured while importing, so nothing has been added to the database. The error is:
zip_fopen failed
```

Manually extracting the encrypted zip and recompressing it into a cleartext archive makes it progress further. However,instead it prompts
```
Failed to derive key. Please check Secure Memory wiki page.
``` 
On console:
```
[INFO] Duplicate element not added
[INFO] Duplicate element not added
Error during key derivation
Encrypting the new data failed, restoring original copy...
Backup copy successfully restored.
Failed to derive key.
Please check <a href="https://github.com/paolostivanin/OTPClient/wiki/Secure-Memory-Limitations">Secure Memory wiki page</a>
```
(Duplicates are expected)

Secure memory has been increased:
```
$ ulimit -l
65536
```

**Comment by 3nprob** [comment]
Did a partial import by reducing `Accounts.txt` to the first 50 lines. They import and show up without error, but the OTP Value is `0` for all of them.

**Comment by paolostivanin** [comment]
Thanks for reporting this. I'll have a look at it!

**Comment by paolostivanin** [comment]
I've installed Auth+ on my phone, but I can't export anything because the app fails.
Can you share with me an example zip? Thanks

**Comment by paolostivanin** [comment]
close due to inactivity
