### ISSUE TITLE
Please add "sort by column" for "Account" and "Issuer" AND make duplication check.

### ISSUE THREAD

**Issue by pm-pm** [paolostivanin/OTPClient#249]
I would be nice to sort "Account" and "Issuer" by clicking on column.
This is helpful to find duplicate entrys.

AND

Add duplication check when adding a "new" list of tokens from an other app.

Example:
1. Add list of 10 tokens in OTPClient. Works fine.
2. Add 1 month later an updated list of 12 tokens.
Now you have 10 duplicate token in the unsorted list. ;-)

Try to implement a solution. :-)
pm-pm

**Comment by paolostivanin** [comment]
Hello,
1) I had to remove this feature to due a bug in gtktreeview. It will come back when (and if) OTPClient will switch to GTK4 (and will be using GtkColumnView)
2) there's already a check in place. But it's very basic: I'm checking the hash of the entry with the hashes in the database. This means that even if a single bit is different, the item is considered as new.

**Comment by paolostivanin** [comment]
close due inactivitty

**Comment by ronjouch** [comment]
@paolostivanin in the absence of a "sort by column" feature, is there a way to **manually** re-order entries?

Having the order be insertion date makes it difficult to quickly find an item when the list grows larger. I'd love to be able to manually re-order my entries in alphabetical Account order, even if hackish / manual / involving manually editing the db. Can you offer a guide for that?

Thanks and thanks for OTPClient!

**Comment by paolostivanin** [comment]
@ronjouch what version are you using? I've added the sorting feature back quite a while ago 😊
You need to press the button with the double arrows (the one on the right of the minus button). Then you can drag and drop rows as you like!

**Comment by ronjouch** [comment]
@paolostivanin ah, sorry, I'm running the old version in Ubuntu LTS, 2.4.4. In this version I don't have a double-arrows button at the right of the minus button.

Sorry not to have checked the changelog or a more recent version, and thanks for the fast reply!

**Comment by paolostivanin** [comment]
Oh, you're really running a very outdated version :O
I guess you're using Ubuntu 18.04, right?
When you will upgrade to either 20.04 or 22.04, you will be able to use my launchpad repo (see the wiki) and always get the latest and the greatest version :)
Unfortunately, due to deps issues, I can't backport newer versions to 18.04.

**Comment by ronjouch** [comment]
> Oh, you're really running a very outdated version :O I guess you're using Ubuntu 18.04, right? When you will upgrade to either 20.04 or 22.04, you will be able to use my launchpad repo (see the wiki) and always get the latest and the greatest version :)

@paolo nope, this is the version shipping in the latest LTS, 22.04! See https://packages.ubuntu.com/jammy/otpclient (And nit: it's actually 2.4.6, not 2.4.4, but I was confused by the title bar that somehow says 2.4.4 :shrug: )

**Comment by paolostivanin** [comment]
Then enjoy https://launchpad.net/~polslinux/+archive/ubuntu/otpclient :)
