### ISSUE TITLE
Feature Request: Show entries as QR-Codes

### ISSUE THREAD

**Issue by clasatau** [paolostivanin/OTPClient#259]
As I use OTPClient as a backup for the authenticator app on my phone, it would be helpful if OTPClient could display its entries as QR-Codes, so that I can easily re-transfer them to my phone in case I should need to set up the app newly.

**Comment by paolostivanin** [comment]
That's a good idea, thanks for the input.
I have to think how to properly integrate this feature, so it will likely be added to v3.1.0 (so in a few months).

**Comment by paolostivanin** [comment]
This feature is being implemented. It will work as follow: once the user has selected a row, by either using the shortcut `Ctrl+O` or by going to `Settings->Show QR Code`
