### ISSUE TITLE
Feature Request: Allow unencrypted database

### ISSUE THREAD

**Issue by narcisgarcia** [paolostivanin/OTPClient#260]
Me and others we already work with full disk encryption and other entire-environment security measures.
This is overall to not having to type in each password for each resource.
There should be an option to not ask for DB password or have it already saved somewhere.

**Comment by paolostivanin** [comment]
If you're using a version >= 2.6.0, then this is already the case. I've added libsecret support, so one can avoid entering the password every time: https://github.com/paolostivanin/OTPClient/wiki/How-to-use-OTPClient#secret-service-integration

**Comment by narcisgarcia** [comment]
This answer needs another feature: An "About" menu option to see application's **version**, license, website, etc.

Debian stable repositories seem to only contain 2.4.x versions.

**Comment by paolostivanin** [comment]
The version is written just under the name on the title bar on the top :smile: 
But agreed, I more complete "about" dialog would be nice.
