### ISSUE TITLE
Switch to libadwaita

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#262]
Replaces the current widgets with the new ones provided by libadwaita >= 1.2

**Comment by mole99** [comment]
First of all great work on OTPClient!

I installed it on my OP6T with postmarketOS + Phosh.

Upon first start the header bar did not correctly scale and I couldn't access the menu to import a token. I managed to scale the application down from a system setting and imported my token. Afterwards I disabled this system setting.

Now the header bar displays just fine. The entries for my token are rather long, but I can scroll to the right and access the OTP value. I can work with this :D

Here you can see OTPClient running on the phone:

![OTPClient](https://user-images.githubusercontent.com/3877395/211500327-294c2182-a900-4cac-b2af-f34f6d631979.jpg)

If I am correct libadwaita provides better scaling for smaller screens. Which could improve OTPClient on phones.

**Comment by paolostivanin** [comment]
Wow, super cool! Never seen OTPClient running a phone, thanks! :smile: 

Yes, libadwaita will improve **a lot** the UX for smaller screen, that's why I planned to switch all possible widgets to it.

Problem is that the porting will take quite a bit (hoping to release something by the end of 2023) because I have to rewrite the whole project from scratch :disappointed:

**Comment by mole99** [comment]
No Problem, I think it's a great fit :D
That sounds like a lot of work. Please take your time!

Yes, I would love to. Just ping me anytime!

**Comment by paolostivanin** [comment]
closed as part of https://github.com/paolostivanin/OTPClient/issues/123
