### ISSUE TITLE
Is there any way to contribute to the translation?

### ISSUE THREAD

**Issue by fv3rdugo** [paolostivanin/OTPClient#263]
Maybe setting the locale is a new feature, in this case, I´m interested in contributing with the translation into another language. 
Warm regards

**Comment by paolostivanin** [comment]
Hello, thank you for offering :) 
Currently, the translation part is not really implemented. Let me fix that and I'll get back to you!

**Comment by paolostivanin** [comment]
All strings are now translatable. The only thing left for me to do is to find out how to generate the po stuff so that translators can easily contribute :smile:

**Comment by paolostivanin** [comment]
@fv3rdugo [here](https://github.com/paolostivanin/OTPClient/tree/dev2_7_0/po) you can find the two pot files to be used as template for translations. When you are done translating, just open a PR (or send me an email, or whatever you prefer) with the `.po` file(s).

Thanks a lot again, really appreciated!

**Comment by fv3rdugo** [comment]
Awesome! I'll get to it as soon as I can, thanks to you.
