### ISSUE TITLE
Cannot Import Aegis.json

### ISSUE THREAD

**Issue by yegnal** [paolostivanin/OTPClient#265]
Tried but unable to import Aegis file, encrypted .json...........

Fedora 37

**Comment by paolostivanin** [comment]
Thanks for reporting this issue. What version of OTPClient and Aegis are you using?

**Comment by yegnal** [comment]
Aegis on Android ver. 2.1otpclient from flathub 2.6.3


    On Monday, November 21, 2022 at 11:19:32 AM EST, Paolo Stivanin ***@***.***> wrote:  
 
 


Thanks for reporting this issue. What version of OTPClient and Aegis are you using?
