### ISSUE TITLE
Export code(s) to Google Authenticator

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [paolostivanin/OTPClient#270]
Hi. Thank you for this grate app.
I looking for any way to export codes to the Google Authenticator. Is there any way?

**Comment by pavelbsd** [comment]
i do not think so.......i've never seen an app do this, but there is a thing you can do. you can export all ur otp to something like freeotp and use a script to generate the qr codes back from that file, then you can use your phone to scan the qr and add it to google authenticator. you have to scan them one by one though......

**Comment by paolostivanin** [comment]
@AmirHosseinKarimi you mean you'd like to import codes in Google Authenticator?

**Comment by paolostivanin** [comment]
I've installed the Authenticator app, and it only allows importing one qrcode at a time.
The qrcode feature will come out soon(ish), see here: https://github.com/paolostivanin/OTPClient/issues/270

But if you wanna bulk import your stuff, then I suggest you switch to a more powerful and better thought app (e.g. Aegis)

**Comment by AmirHosseinKarimi** [comment]
Hi Paolo. Yes, I tried to do it before. But now, I installed Aegis instead of Google Authenticator.
Anyway, Glad to hear about the new feature to export keys as QRcode.
