### ISSUE TITLE
[Aegis] An error occured while imorting Aegis encrypted json

### ISSUE THREAD

**Issue by giovEra** [paolostivanin/OTPClient#276]
OS: OpenSUSE Tumbleweed
OTPClient: v3.1.1 (from official openSUSE repo)
Aegis: 2.1.2 (from F-Droid)

When I try to import an encrypted json from Aegis I get this (generic) error:

[![OTPClient-Aegis.jpg](https://i.postimg.cc/y8XBDMkD/OTPClient-Aegis.jpg)](https://postimg.cc/gxJ15Byp)

Do you have any ideas on how to solve it?
If more information is needed, I am available.

**Comment by paolostivanin** [comment]
Hello,
thanks for reporting this. I'll have a look at it today or tomorrow! 

BR

**Comment by giovEra** [comment]
Very fast response!
Thanks for taking a look at it.

**Comment by paolostivanin** [comment]
I'm also using Aegis on my phone. I've just tried to import the encrypted json, and it works fine for me (also on Tumbleweed using latest OTPClient and Aegis).

Can you try to execute it from the terminal and see if it outputs something more?

**Comment by giovEra** [comment]
That is the output:
```
user@laptop:~> otpclient

(otpclient:22394): GLib-GIO-CRITICAL **: 18:48:29.161: Error while sending AddMatch() message: The connection is closed

(otpclient:22394): GLib-GIO-CRITICAL **: 18:48:29.161: Error while sending AddMatch() message: The connection is closed

(otpclient:22394): GLib-GIO-CRITICAL **: 18:48:29.161: Error while sending AddMatch() message: The connection is closed
Terminated
```

**Comment by paolostivanin** [comment]
Hmm, that doesn't help me much. If I were to provide you a more verbose version, would you be able to compile it yourself?

**Comment by paolostivanin** [comment]
Nice, then I'll work something out for tomorrow to help debugging

**Comment by giovEra** [comment]
I invite you not to take it easy. I am not in a hurry :)

**Comment by giovEra** [comment]
I took a look at it and the error occurs in line [125](https://github.com/paolostivanin/OTPClient/blob/master/src/common/aegis.c#L125). The value returned is 16777226 instead of 0.

The strange thing is that it does not generate any message the line [127](https://github.com/paolostivanin/OTPClient/blob/master/src/common/aegis.c#L127).

How I got this information:
I modified aegis.c in this [way](https://pastebin.com/26Y0ZG9S), and got this [output](https://pastebin.com/DRM0qJhz).
(I also printed out the macros to compare them with the value of the errors)

---
Note:
To make sure the backup was not corrupted, I tried restoring it to two android devices, and it imported correctly.
And the password is also correct because I stored it in a KeepassXC database.

**Comment by paolostivanin** [comment]
The `gpg_err`  returned by `gcry_cipher_checktag` is converted to a `gcry_err_code` via `gcry_err_code`, and that last one returns `10` which is equivalent to `GPG_ERR_CHECKSUM`.
So now, questions for myself:
1. why is this happening if the file can be imported by other software?
2. why is the error not being set on the popup?

Question for you:
* does you pwd contains non standard chars? (e.g. greek symbols, chinese symbols, umlaut, etc)?

**Comment by paolostivanin** [comment]
I found out with the error was not printed in the dialog, and that is fixed. Still, ATM I have no idea why the import fails.

**Comment by paolostivanin** [comment]
It must be something related to the input password.
1. can you try to export the file using a letters and numbers only pwd? Does it work?
2. if the previous one worked, can you tell me what kind of chars your input pwd has?

**Comment by giovEra** [comment]
Import works with passwords of length 32 consisting only of `A-Za-z0-9`.

**Comment by paolostivanin** [comment]
AFAIR, max pwd length should be 255, but I'm going by memory (it was done long ago).
I'll double check that and also why it's not allowing a pwd with standard chars.

Thanks a lot

**Comment by giovEra** [comment]
Ok, thanks :)

note: I have try  passwords of length 254 consisting only of `A-Za-z0-9` but import not work :)

**Comment by paolostivanin** [comment]
The issue with long pwds occurs during key derivation. Why is still a mystery though...

**Comment by paolostivanin** [comment]
The issue is reproducible when the input pwd is > 64 chars :thinking:

**Comment by paolostivanin** [comment]
well, it's done :smile: bug has been squashed!
The issue was that, for Aegis, the `NUL`  char shouldn't be part of the key derivation. Why it worked for strings <= 64 I have no idea :see_no_evil:

**Comment by paolostivanin** [comment]
@giovEra can you compile latest master and confirm that everything is fixed? Thanks a lot :smile:

**Comment by giovEra** [comment]
I compiled the master branch successfully, and tested the import with passwords of 254 characters length and confirm that it works.

Thank you for the fix!

When you have time, I invite you to make a pull request to the opensuse factory so that the fixed version will be available for download from the openSUSE official repo. Thanks again.

**Comment by paolostivanin** [comment]
Thanks for confirming it :)
Yes, don't worry! I'm the official maintainer of otpclient for openSUSE, so it will always be up to date ;)
