### ISSUE TITLE
OTPClient crashes/shuts down on its own.

### ISSUE THREAD

**Issue by Giger22** [paolostivanin/OTPClient#286]
System 
Arti linux 6.1.8-artx1-1
KDE Plasma 5.26.5
Wayland
Application always crashes down after few seconds of running. I have the newest version 3.1.4. 

**EDIT**
I had to change option "Can run in the background" in the Flataseal to fix this. I do not know if it should be like that.

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'm looking into it.

**Comment by paolostivanin** [comment]
Hi,
I've tried on some known distros (Ubuntu, Fedora, openSUSE) and I'm not able to reproduce this issue.
Must be some weird configuration on Arti. Sorry, can't really help here!
