### ISSUE TITLE
Dark theme does not work.

### ISSUE THREAD

**Issue by Giger22** [paolostivanin/OTPClient#287]
System
Artix linux 6.1.8-artix1-1
KDE Plasma 5.26.5
Wayland
I have option "Dark theme enable" turned on but I still have light theme visible.

**Comment by paolostivanin** [comment]
This is an issue with KDE and GTK theming, but I can't help you because I use only GNOME.
OTPClient has been developed with GNOME in mind, so it will work the best there. I can't support every DEs out there, I'm sorry.
