### ISSUE TITLE
Wrong app-id

### ISSUE THREAD

**Issue by TingPing** [paolostivanin/OTPClient#29]
In `main.c` you use `org.gnome.OTPClient` instead of `com.github.paolostivanin.OTPClient`.

**Comment by paolostivanin** [comment]
Hello,
no, I'm using the correct one :) (https://github.com/paolostivanin/OTPClient/blob/master/src/main.c#L19)

**Comment by TingPing** [comment]
Oops, must have been looking at an old commit.
