### ISSUE TITLE
issues with settings (Dark Theme on systems using Dark Theme)

### ISSUE THREAD

**Issue by jlariviere1** [paolostivanin/OTPClient#293]
Dark theme does not function properly.  
I'm running what appears to be the latest version from flathub (3.1.6) on Manjaro.  
If I set my system to use dark theme (Adwaita-dark), then OTPClient uses light.  If I set the system to light (Adwaita), then OTPClient does use the dark theme. 
Thanks, 

![image](https://user-images.githubusercontent.com/29808661/227077087-5068ca20-4031-404c-ad41-19eb13eb4017.png)

![image](https://user-images.githubusercontent.com/29808661/227077029-13b3f199-97de-4fc7-9a60-9cd053e2bc17.png)

**Comment by paolostivanin** [comment]
I'm sorry, but OTPClient is developed for the GNOME desktop. I can't chase all the various desktop environment differences (XFCE, KDE, LXDE, E17, etc), so I'm sticking with what I'm using.
I don't have enough free time to support all of them, but a PR is always welcome :smile:
