### ISSUE TITLE
OTPClient segfaults on "Show QR-Code" when no row is selected

### ISSUE THREAD

**Issue by philfry** [paolostivanin/OTPClient#295]
Hi and thanks for the great tool!

As mentioned in the title, OTPClient segfaults when no row is selected. IMHO "Show QR-Code" should be greyed out / non-clickable then.

Best,
Phil

**Comment by paolostivanin** [comment]
works fine here! can you tell me: OS, flatpak/not flatpak, otpclient version?

**Comment by paolostivanin** [comment]
you're right! let me fix that!
