### ISSUE TITLE
Aegis plaint text import isn't working

### ISSUE THREAD

**Issue by kbmetz** [paolostivanin/OTPClient#296]
I'm trying to export my OTP from Google auth. I've tried exporting it as a png and also I've tried using Aegis to export. I was able to import using the Aegis app so I know the png image is working. How-ever OTP client says there is no QR code in the PNG. And when I tried to import using the Aegis plan JSON I get 'An error occured while importing, so nothing has been added to the database. The error is: wrong arguments'. This what from the gui and clicking the Import -> Aegis plan json.

This is running on the Postmarket OS on a pine phone pro.

**Comment by paolostivanin** [comment]
Hello,
I've just tried and it works fine. I've used the Google Authenticator app to generate the png, scanned it with the webcam using "Import -> Google QR -> From webcam" and the code was correctly added.

**Comment by Alex9001** [comment]
I can't import Aegis plain json. When I try it says:

An error occurred while importing, so nothing has been added to the database. The error is:
wrong arguments

**Comment by kbmetz** [comment]
> I can't import Aegis plain json. When I try it says:
> 
> An error occurred while importing, so nothing has been added to the database. The error is: wrong arguments
> 
> using Artix x64

This is the issue I'm having

**Comment by paolostivanin** [comment]
@kbmetz sorry, I understood you were having troubles importing google qrcodes!

let me have a look at aegis then
