### ISSUE TITLE
Compiling from source on Pinephone Pro running Mobian

### ISSUE THREAD

**Issue by kbmetz** [paolostivanin/OTPClient#299]
Thank you for keeping this client updated. Just wanted to offer the steps I ran to get this installed on a Pinephone Pro running Mobian. Please feel free to add this to the wiki or just close the issue if it's not needed. Just wanted to offer it to others and to say thank you for keeping an updated app

The following command will need to be run on the command line of the Pinephone (pro). I enabled ssh to make it easier. Also, run these before the instructions listed

sudo apt install -y build-essential git cmake pkg-config \
libprotobuf-c-dev libprotobuf-dev libgcrypt20 libgcrypt20-dev \
libcotp-dev libcotp12 libbaseencode-dev libbaseencode1 libpng-dev \ 
libjansson-dev libzbar-dev zbar-tools libgtk-3-dev \
libsecret-1-0 libsecret-1-dev libqrencode-dev qrencode 

After everything is installed, you can simply follow the instructions listed starting at the git pull

**Comment by paolostivanin** [comment]
thanks a lot, really appreciated :) https://github.com/paolostivanin/OTPClient/wiki/Pinephone-Pro
