### ISSUE TITLE
OTPClient gives wrong codes when system time is local time

### ISSUE THREAD

**Issue by rogerkeays** [paolostivanin/OTPClient#304]
My system clock uses the local time instead of the tradition UTC, and I found that my TOTP codes from otpclient don't work. Does otpclient support this configuration? Maybe I am doing something else wrong. My clock is accurate to 2 seconds.

version 2.4.2 (debian 10)

**Comment by paolostivanin** [comment]
Hello,
OTPClient (well, libcotp to be correct) doesn't care about whether your clock is configured using localtime or UTC. It simply gets the current time and uses that to generate the totp. If the system clock is not correct, there's nothing we can do about it.
I'm not really sure how to help here 🤔

**Comment by rogerkeays** [comment]
Got it working. I think the website broke because I hit the back button. Thanks for the help anyway.

**Comment by rogerkeays** [comment]
Closing as invalid.
