### ISSUE TITLE
[Feature request] Add sorting.

### ISSUE THREAD

**Issue by RDKRACZ** [paolostivanin/OTPClient#319]
The app is lacking ability to sort entries alphabetically by issuer and account.

Reordering 250+ tokens manually is impossible thing to do. I would need to write a Python script to reorder the tokens and then import them as I believe the tokens in the app are in the .json file order.

**Comment by paolostivanin** [comment]
hello,
see point 1 [here](https://github.com/paolostivanin/OTPClient/issues/249#issuecomment-1166912203)
