### ISSUE TITLE
[Feature request] More import options

### ISSUE THREAD

**Issue by K0-RR** [paolostivanin/OTPClient#322]
The following open-source apps are popular solutions for 2FA so importing from them would allow more users to switch to this app. Ratings and download data are from the Play Store:
-[KeePassXC](https://keepassxc.org/) - there are multiple clients for Android supporting OTP
-[Bitwarden](https://github.com/bitwarden) - &emsp;&emsp;&emsp; rating is 4.3; 44.7K reviews; 1M+ downloads
-[2FAS](https://github.com/twofas) - &emsp;&emsp;&emsp;&emsp;&emsp; rating is 4.8; 29.6K reviews; 1M+ downloads
-[Authenticator Pro](https://github.com/jamie-mh/AuthenticatorPro) - rating is 4.5; 1.78K reviews; 100K+ downloads

Aegis for comparison: rating: 4.9; 3.34K reviews; 100K+ downloads

**Comment by paolostivanin** [comment]
Thanks for reporting this! I'll look into 2FAS and Authenticator Pro.

**Comment by edouard-lopez** [comment]
Since [Authy announced it was sunsetting desktop app](https://news.ycombinator.com/item?id=39360439), people are looking for an alternative and someone [suggested OTPClient in 2Fas repo](https://github.com/twofas/2fas-android/issues/107#issuecomment-1947927866) but unfortunately, none of the above are supported.

Do you plan to work on it?

**Comment by paolostivanin** [comment]
I can't find any documentation about the backup format, therefore I can't implement it.

**Comment by paolostivanin** [comment]
https://github.com/twofas/2fas-android/issues/117

**Comment by paolostivanin** [comment]
note to self:
* https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/importers/AuthenticatorProImporter.java
* https://github.com/beemdevelopment/Aegis/blob/master/app/src/main/java/com/beemdevelopment/aegis/importers/TwoFASImporter.java

**Comment by paolostivanin** [comment]
all done, all tested. Release with those 2 new providers should come out in the next days.

**Comment by paolostivanin** [comment]
Reported issue for AuthenticatorPro: https://github.com/jamie-mh/AuthenticatorPro/issues/1101

**Comment by paolostivanin** [comment]
To-Do:
- [ ] fix 2FAS export not working
- [ ] fix/wait for a fix for AuthPro

**Comment by Spacellary** [comment]
> all done, all tested. Release with those 2 new providers should come out in the next days.

@paolostivanin 

Well done!

**Comment by paolostivanin** [comment]
Still waiting on 2FAS team about the issue mentioned on their github. No answer atm.

**Comment by paolostivanin** [comment]
all done and tested :smile:
