### ISSUE TITLE
All TOTPs suddenly become incorrect

### ISSUE THREAD

**Issue by YuruiHong** [paolostivanin/OTPClient#326]
I use OTPClient on a local PC, parallelly to Aegis on Android. When I tried to use the TOTP credentials from OTPClient today, I find that they are completely different from that on Aegis, which turned out to be correct. How this happened and is it possible to recover valid TOTP credentials. I can't imagine what would happen if I depend on this alone.🤣

OS:  Debian 6.5.13-1 (2023-11-29) x86_64 GNU/Linux
OTPClient: v3.2.1

**Comment by paolostivanin** [comment]
Did you update libcotp? If so, you need to recompile also OTPClient.
Then check the system time. I see no other possible causes tbh.
