### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by izzylaif** [paolostivanin/OTPClient#327]
Weill it be too much of a hassle to have a Windows release as well?
Other projects like WinAuth have long been abandoned, and sadly there is no desktop opensource alternative

**Comment by paolostivanin** [comment]
yes, it would! Unfortunately, I have no plans at all to support Windows and MacOS (https://github.com/paolostivanin/OTPClient/issues/209).

**Comment by izzylaif** [comment]
Ok, I've made the decision to move away from OTPclient to KeepassXC for OTP, which ships both as an Linux appimage and Windows portable build to be practically secure and easy to backup.

Thank you for everything.
