### ISSUE TITLE
Secret can contain only characters from the english alphabet and digits. (Amazon account)

### ISSUE THREAD

**Issue by Niccolo-Marcucci** [paolostivanin/OTPClient#328]
I have a TOTP from and amazon.it account that I'm unable to use on this app.

I can successfully add the secret if I scan the corresponding QR, but the app does not generate the OTP code. More specifically, when I click on the OTP field the code does not appear. I get the message "OTP copied on clipboard", but nothing is actually copied.

If I try to add manually the secret i get the message "Secret can contain only characters from the english alphabet and digits.".
In facts, the secret in question appears to have some "=" symbols trailing at the end of it. If I try removing those, the OTP works, but (I guess obviously) the resulting value is wrong.

Is there a reason why symbols are not allowed? Is (unsurprisingly) amazon breaking any standard?
P.S. This might be related to #172

OS: Ubuntu 22
App version: 2.4.6 
App repo: ubuntu-jammy-universe

**Comment by paolostivanin** [comment]
hello,
you are using an ancient version of the application that is no longer supported. Can you please update to the latest version? I have a PPA for LTS releases: https://launchpad.net/~polslinux/+archive/ubuntu/otpclient

**Comment by Niccolo-Marcucci** [comment]
Yep! That was indeed an ancient version.

I added the repo, updated and that solved the issue.
I can now add the key via QR, and get the correct code. 
If I add the secret key manually i get the same error as before, but, by removing the trailing "=" symbols, this time i get the correct code.

Thanks a lot for the fast response.

**Comment by paolostivanin** [comment]
I'll look into why this is happening when manually added. Thanks!
