### ISSUE TITLE
Does not start after update to 3.2.1 via PPA

### ISSUE THREAD

**Issue by timur-g** [paolostivanin/OTPClient#330]
Otpclient does not start in Linux Mint/Ubuntu 22.04 after update of otpclient to 3.2.1 and libcotp2 to 3.0.0. via PPA:
otpclient/jammy 3.2.1-0ubuntu1~jammy2 amd64 [upgradable from: 3.2.1-0ubuntu1~jammy1]
libcotp2/jammy 3.0.0-0ubuntu1~jammy1 amd64 [upgradable from: 2.0.1-0ubuntu1~jammy1]

error while loading shared libraries: libcotp.so.2
2.0.1 is not available.

PPA is:  https://ppa.launchpadcontent.net/polslinux/otpclient/ubuntu

**Comment by paolostivanin** [comment]
Bear with me while I figure out packaging issues. I'm not really used to that launchpad stuff. Hope to solve everything in a couple of hours

**Comment by timur-g** [comment]
Resolved with removing and installing again. Simple apt --reinstall did not help me.

**Comment by paolostivanin** [comment]
Glad to hear that. Still, I've found some packaging bugs and I have to fix them.

**Comment by timur-g** [comment]
I saw another update, and here is the result:

Unpacking otpclient (3.2.1-0ubuntu1~jammy4) over (3.2.1-0ubuntu1~jammy3) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libcotp3_3.0.0-0ubuntu1~jammy3_amd64.deb
 otpclient : Depends: libcotp3 (>= 3.0.0) but it is not going to be installed

Fixed by removing  otpclient  libcotp2 and installing otpclient which installed libcotp3.

**Comment by paolostivanin** [comment]
It should be finally solved with the jammy4 rebuild!
