### ISSUE TITLE
halp? libcotp.so.2 error since upgrade to 3.2.1

### ISSUE THREAD

**Issue by asanghc** [paolostivanin/OTPClient#331]
"otpclient: error while loading shared libraries: libcotp.so.2: cannot open shared object file: No such file or directory"

This is on an Arch based distro, and it lies because the library is there..
I tried removing and re-installing 3.2.1. > No change.
So I rolled back to old version 2.4.7 and it works for now but I'm not smart enough to figure out what is or isn't happening.

**Comment by paolostivanin** [comment]
That's happening because you must first update libcotp to version 3.0.0 and then recompile OTPClient.

**Comment by paolostivanin** [comment]
Then the maintainers forgot to trigger a recompile of OTPClient. The issue is that OTPClient is still compiled against the old libcotp (V2), while you have V3 installed.
Recompiling OTPClient will fix the issue. You should open a bug at your distro bug tracker
