### ISSUE TITLE
OTPClient keeps crashing when trying to import; Also cant import one of my TOTP entries, otpclient wont import it

### ISSUE THREAD

**Issue by dimyself** [paolostivanin/OTPClient#332]
I exported my TOTP entries from Aegis (json plain text not encrypted) and imported into otpclient...However one of the entries isn't getting imported. I've even tried erAsing all entries except the one that isn't getting imported

Everytime i try to import anything, otpclient crashes with segmentation fault...also when i try to manually add an entry, it crashes.

I set the ulimit to unlimIted.

`
> otpclient
Truncation occurred.
Truncation occurred.
(otpclient:19164): GLib-GIO-CRITICAL **: 23:17:38.408: GFileInfo created without standard::content-type
(otpclient:19164): GLib-GIO-CRITICAL **: 23:17:38.408: file ../glib/gio/gfileinfo.c: line 1822 (g_file_info_get_content_type): should not be reached
Segmentation fault (core dumped)

`

Here's the totp json entry that otpclient wont import for some reason:

`
{
    "version": 1,
    "header": {
        "slots": null,
        "params": null
    },
    "db": {
        "version": 2,
        "entries": [
            {
                "type": "totp",
                "uuid": "<letters_numbers_and_dashes>",
                "name": "Bitrue",
                "issuer": "Bitrue",
                "note": "",
                "favorite": false,
                "icon": "<long_string_letters_numbers_chars>+<another_string>==",
                "icon_mime": "image\/svg+xml",
                "info": {
                    "secret": "<letters_numbers_string>",
                    "algo": "SHA1",
                    "digits": 6,
                    "period": 30
                }
            }
        ]
    }
}
`

I'm running the latest version on Arch linux (3.2.1-3)

Thank you!

**Comment by paolostivanin** [comment]
Thanks for reporting this. I'll have a look at it (hopefully) next week!

**Comment by dimyself** [comment]
Thank you very much! Please let me know if theres something I can try to do
on my end or if theres any other info you need

**Comment by paolostivanin** [comment]
I was able to successfully import that json that you provided. I need something more close to real in order to reproduce the issue.
