### ISSUE TITLE
Change database: Pressing OK without choosing a file does not prompt for file again

### ISSUE THREAD

**Issue by f-fusco** [paolostivanin/OTPClient#335]
Steps to reproduce:
- Start with empty data 
- At the password window, click "Cancel"
- Click on "Select another db"
- At the "Change database" window, click "OK" without choosing a file

At this point you get the message:
"Selected file is either a symlink or a non regular file. Please choose another file."

Pressing OK won't prompt to choose another file, instead creating an empty DB.

Version 3.2.1 flatpak.

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'll fix it ASAP.
