### ISSUE TITLE
Blank window when entering empty password

### ISSUE THREAD

**Issue by f-fusco** [paolostivanin/OTPClient#336]
Steps to reproduce:

- Start with empty data
- Press "Cancel" at the choose password prompt
- Press "Select another DB"
- Choose a random file and press OK
- Enter a blank password and press OK

First bug:
- You have to press OK 2 times to close the message "Either the file is corrupted or the password is wrong".

Second bug:
- Press "Cancel" at the password prompt
- Press "Select another DB" again
- Be met with a blank "Change database" window
![Schermata del 2024-01-08 15-34-02](https://github.com/paolostivanin/OTPClient/assets/22770482/11bb5eb2-7198-4a7a-b1f7-96ecf042b1b6)

Upon closing the blank window, you get "Error during key derivation". At this point trying to select another DB always greets you with this blank window, making it impossible from the GUI to choose a proper DB file.

Version 3.2.1 flatpak.

**Comment by paolostivanin** [comment]
Thanks for reporting this, I'll fix it ASAP.
