### ISSUE TITLE
[Feature request] Add command-line argument to start OTPClient with a certain database

### ISSUE THREAD

**Issue by zeitgenosse** [paolostivanin/OTPClient#340]
I regularly switch between databases. Currently, I have to open OTPClient and enter the password to unlock database1. Then I have to click on “Change database”, select it from the file selection dialogue and enter the password to unlock database2. Same when I switch back to database1.

My proposal is to enable giving the database I want to use as a command-line argument, e.g.

```
otpclient --database="~/database2.enc"
```

**Comment by paolostivanin** [comment]
Fantastic idea, I'll for sure implement it!
