### ISSUE TITLE
Error while loading json data: end of file expected near '@'

### ISSUE THREAD

**Issue by edwardando** [paolostivanin/OTPClient#341]
After successfully importing URIs from freeOTP+ into clean database.
On releaunching I get this message, any thoughts?

This is on a regular Debian 12

**Comment by edwardando** [comment]
OK this is related to having the "@" character in the account field,
which of which about half of my TOTPs have (a reference email address).

This seems like quite a strong limitation...

**Comment by paolostivanin** [comment]
Hello,
this is a **free and open source** software developed on my **own free time** and kindly shared with the world.
Having said that, if you don't like it or are having troubles with it you can either:
* use another one of the thousands solutions out there

or

* open a **useful** and **respectful** issue here on GitHub

Regards

**Comment by edwardando** [comment]
Hi @paolostivanin again, how would you like it to be more respectful?
This is a serious bug which I believe it's worth knowing about.
If you don't accept issues, that's OK, just say it.

**Comment by paolostivanin** [comment]
Seems like I do accept issues (that are written in a respectful way): https://github.com/paolostivanin/OTPClient/issues?q=is%3Aissue+is%3Aclosed

**Comment by paolostivanin** [comment]
cannot reproduce, please try with the latest version. If the issue persists, please provide a reproducer, thanks.
