### ISSUE TITLE
Segfault on "generate QR code"

### ISSUE THREAD

**Issue by edwardando** [paolostivanin/OTPClient#342]
Segfaults are bad

**Comment by edwardando** [comment]
Hi @paolostivanin how would you like it to be more respectful?
As you can read from the other issue I'm on Debian 12.
A segfault is a segfault, and I cannot provide much more debugging information...

**Comment by paolostivanin** [comment]
cannot reproduce, please try with the latest version. If the issue persists, please provide a reproducer, thanks.
