### ISSUE TITLE
Error while loading json data: end of file expected near '@'

### ISSUE THREAD

**Issue by edwardando** [paolostivanin/OTPClient#343]
Here is a respectful attempt at reporting bug #341 

- I am running a clean debian 12
- I have installed optclient from debian's official repositories
- I have exported URIs from FreeOTP+ on my phone as a txt file

I launch `OTPclient`
- I make a new `OTPclient` database
- I import my TOTPs from the textfile as exported from phone
- Everything appears OK in the main window.
I close `OTPclient`.

On relaunching I have the follwing error:

> Error while loading json data: end of file expected near '@'

I have looked into this, and it's due to the @ symbol in the "Account" field which is unfortunately quite common since accounts are often email addresses.
Can you confirm this bug? Does it not happen with other import mechanisms?

**Comment by paolostivanin** [comment]
are you using the latest version?

**Comment by edwardando** [comment]
I'm using 3.1.4 from the debian 12 repo

**Comment by paolostivanin** [comment]
please try again with the latest version since that one is no longer supported (https://github.com/paolostivanin/OTPClient/security/policy)

**Comment by paolostivanin** [comment]
cannot reproduce, please try with the latest version. If the issue persists, please provide a reproducer, thanks.

**Comment by edwardando** [comment]
It is indeed fixed in 3.4.0
