### ISSUE TITLE
Update Linux dist page

### ISSUE THREAD

**Issue by mixmastamyk** [paolostivanin/OTPClient#347]
Was looking for this app Fedora.  Didn't find it.  Your wiki says:

https://github.com/paolostivanin/OTPClient/wiki/Tested-OS-&-Packages#packages

But the Fedora entry is wrong, has Suse info.  Couldn't update the wiki, not sure why.  Read-only wiki is not much of a wiki.  :-)

I found this here, not sure of the version:

https://copr.fedorainfracloud.org/coprs/dgraef/OTPClient/

Is this copr repo reliable?

**Comment by paolostivanin** [comment]
Hello,
I've updated the wiki page with some clarifications. The fact it's hosted in opensuse.org doesn't matter :smile: our build system (OBS) can build stuff for lots of different distros, Fedora included.

I wasn't aware of the copr repo. It's providing an outdated version though, so I suggest you stick with the version I maintain until the copr one is officially maintained.

**Comment by paolostivanin** [comment]
About read-only wiki, I had to do that because I had spammers editing and removing content :disappointed:

**Comment by mixmastamyk** [comment]
Thanks!

**Comment by mixmastamyk** [comment]
Now getting this error when trying to use that repo:

```
⏵ sudo dnf install otpclient
...
Public key for libcotp3-3.0.0-1.32.x86_64.rpm is not installed
Public key for otpclient-3.4.0-1.13.x86_64.rpm is not installed
...
Error: GPG check FAILED
```

**Comment by mixmastamyk** [comment]
This prevented my system from updating for weeks, plus another half hour to figure this out:

```
sudo rpm --import \
https://download.opensuse.org/repositories/home:/polslinux:/otpclient/Fedora_39/repodata/repomd.xml.key
```

No mention anywhere, even on OBS.  Did I miss it?

**Comment by paolostivanin** [comment]
thanks, I've updated the wiki!

**Comment by paolostivanin** [comment]
hello,
I've now added Fedora 40, so please use that :)
It will be available in max 1h from now

**Comment by mixmastamyk** [comment]
Thanks.
