### ISSUE TITLE
otpclient-cli 3.4.1 on Ubuntu 20.4 not displaying token

### ISSUE THREAD

**Issue by jcbradfield** [paolostivanin/OTPClient#356]
Can't find a mention of this here or on the web - apologies if I've missed it.

Ubuntu 20.4.6 LTS moved otpclient-cli to 3.4.1-0ubuntu1~focal1 from 3.2.1 recently, and now it no longer displays any token:
```
high: /usr/bin/otpclient-cli show -a "University of Edinburgh:jcb@ed.ac.uk" -n 
Type the DB decryption password: 
high: 
```

**Comment by paolostivanin** [comment]
That's weird since no changes have been made to that part of the code. Mostly bug fixes and GUI improvements.
Can you do a `ldd /usr/bin/otpclient-cli | grep -i cotp` please?

**Comment by paolostivanin** [comment]
OTPClient 3.4.0 brought a new CLI implementation (please check the release notes). You can see the new commands with `otpclient-cli -h`

**Comment by jcbradfield** [comment]
Shouldn't it give an error message if the previous syntax is no longer valid syntax?
