### ISSUE TITLE
Filter bar and item sorting

### ISSUE THREAD

**Issue by wiryonolau** [paolostivanin/OTPClient#357]
Hi possible to add filter bar / search bar 

OS is Debian 12 using default apt repo version otpclient 3.1.4 

I cannot ```ctrl + F``` without clicking on one of the otp account first which also reveal the code.
If there is multiple similar account name I also cannot search the next one 
Sorting by account / issuer will be nice

**Comment by paolostivanin** [comment]
That's scheduled for v4 :smile: not sure if I'll also have time to developing it for v3.
