### ISSUE TITLE
Switch to Argon2id

### ISSUE THREAD

**Issue by elliotwutingfeng** [paolostivanin/OTPClient#358]
Would you be open to switching to Argon2id over 100k iterations of PBKDF2? It would provide better protection for weaker vault passwords.

**Comment by paolostivanin** [comment]
Sure, I'll think about it. I need to check whether this enhancement is worth the time and effort. I may even think to make this customizable, but then it would require a DB change :thinking: 
No idea, let's see with what I will come up with.

**Comment by paolostivanin** [comment]
This would be compatible with current Debian stable and greater and Ubuntu >= 23.10.
If I decide to implement this change, it will have to be configurable in order to support older distros.

**Comment by paolostivanin** [comment]
The switch to Argon2id will happen. I have yet to figure out some minor design things, but it will likely happens before end of summer.

**Comment by paolostivanin** [comment]
To-Do:
- [ ] change db format to support configurable security
- [ ] make db security configurable
- [ ] switch to argon2id by default
