### ISSUE TITLE
Auto Lock on is enabled and can't disable

### ISSUE THREAD

**Issue by terashy88** [paolostivanin/OTPClient#362]
Since recently, `otpclient` is always enable without the need to unlock it. 

The settings for `Auto lock on system lock` and ` Auto lock when inactive` are gray out.

How to make use again of it?

**Comment by terashy88** [comment]
so no solution

**Comment by paolostivanin** [comment]
The solution is at the top of the issue page here on GitHub:
 https://github.com/paolostivanin/OTPClient/issues/275

I also would like to remind you that I'm the **only** developer of this **free and open source software** that, as stated in the license, comes without any support or warranty. So do not gives for granted the *free* support I give out to people on my *free and spare time*.

So, please, more "thank you" and less passive aggressive comments in future.

Thanks

**Comment by terashy88** [comment]
Can't see anything aggressive on my comment
