### ISSUE TITLE
Minimize/close to notification area feature

### ISSUE THREAD

**Issue by kiukiucat** [paolostivanin/OTPClient#363]
Great program, happy to have discovered this. Only suggestion is to add a minimize/close to notification area feature one may opt into using. Thank you.

**Comment by paolostivanin** [comment]
GNOME doesn't support notification area. It's possible to get some functionality back using some extensions, but with GTK4 app this will no longer be possible.
Sorry, but I won't invest time on this feature knowing that it will not work with GTK4 and greater.
