### ISSUE TITLE
Import from google does not works

### ISSUE THREAD

**Issue by MyrikLD** [paolostivanin/OTPClient#364]
1. 30 seconds - too short window to scan even first page of google import qr code. The camera takes a long time to stabilize the brightness. After this, the warning window disappears, and when you close the camera window, the camera remains on; the only solution is to restart the application.
2. Is it really impossible to understand that this is a Google import based on the string received from qr? Why a separate menu for this?
3. Open screenshot from phone impossible too - app dont know how to open jpeg file, only png. It is very sad.
4. If it is not possible to adequately implement qr reading, can you at least do a text import? There are a huge number of applications that can get text from qr.

**Comment by paolostivanin** [comment]
Hello,
1. I've increased the timeout to 60s and fixed the bug were the camera, under certain conditions, would remain open
2. no, it's not impossible. It would require some refactoring on my side though. I'll think about it.
3. I could add jpeg support (or auto conversion from jpeg to png). I'll think about it

**Comment by paolostivanin** [comment]
Done:
- [ ] increased the timeout to 60s and fixed the bug were the camera, under certain conditions, would remain open
- [ ] add jpeg support

To-Do:
- [ ] merge google with qr main handling
