### ISSUE TITLE
otpclient: with FreeOTP+ export, spaces in key URIs are not encoded

### ISSUE THREAD

**Issue by fvcr** [paolostivanin/OTPClient#367]
Hi @paolostivanin,

When using Export → FreeOTP+ (key URI), the URIs in the generated file
have raw space characters. Such characters should be encoded as %20.

Please, see:
https://bugs.debian.org/1074263

Maybe you can tell us if this happens on your side too.

Thanks!

**Comment by paolostivanin** [comment]
internally, it's using `g_uri_escape_string` to generate the escaped string. I'm on Tumbleweed, therefore I'm using the latest `2.80.3`. Dunno if it may be an issue with glib. I can try on older Leap...

**Comment by paolostivanin** [comment]
I'll check on Debian testing what's going on

**Comment by paolostivanin** [comment]
Can confirm that it works fine for me also on Debian testing

**Comment by vinc17fr** [comment]
Apparently the issue occurs only for the issuer. For instance:
```
otpauth://totp/test%20123%3Atest%20123?secret=GEZDGNBVGY3TQOIK&issuer=test 123&digits=6&algorithm=SHA1&period=30
```
The space for the account is correctly encoded, but not the one for the issuer.

**Comment by paolostivanin** [comment]
ahhh found the issue! Will fix it asap, thanks @vinc17fr

**Comment by fvcr** [comment]
I've reproduced on both debian 12.5, testing and unstable.

Maybe that will help,

You can generate a base32 encoded string like this:
$ echo 123456789 | base32
MVRWQ3ZAGEZDGNBVGY3TQOIK

And add a new token manually:
Add token > Manually
TOTP - SHA1 - Account: "test 123" - Issuer: "test 123" - Secret: MVRWQ3ZAGEZDGNBVGY3TQOIK - Digits: 6 - Period: 30
![f1dae1480466927cb57d9bc3a191b13e](https://github.com/paolostivanin/OTPClient/assets/59065937/6f073e8a-aca2-415f-82fd-7f38f5d4daa1)

Export > FreeOTP+ (Key URI)
It generated a file called freeotpplus-exports.txt, with the content:

otpauth://totp/test%20123%3Atest%20123?secret=MVRWQ3ZAGEZDGNBVGY3TQOIK&issuer=test 123&digits=6&algorithm=SHA1&period=30

The same content I showed in the [bug](https://bugs.debian.org/1074263).

In my opinion, the field **issuer** is coming with uncoded space.
