### ISSUE TITLE
OTPClient is treated as a leftover by Garuda (Arch)

### ISSUE THREAD

**Issue by meatspinner** [paolostivanin/OTPClient#370]
Whenever I use the option to clean unnecessary, orphan packages 
`sudo pacman -Qdtq | sudo pacman -Rns -` or `sudo pacman -Rns $(pacman -Qtdq)`, both otpclient as well as libcotp show up as packages safe to uninstall.

Its not a big deal but thought it was a good idea to let you guys know and maybe try to "fix" this in the future.

**Comment by paolostivanin** [comment]
hello,
I don't use Arch, so I have no idea how to fix this, sorry.
If you have any suggestion, feel free to write it here so that I can update the PKGBUILD :smile: 

Thanks

**Comment by meatspinner** [comment]
I don't know either tbh, it was just a suggestion anyway since its not really a big deal.
