### ISSUE TITLE
Import from Aegis with custom icons causes crash

### ISSUE THREAD

**Issue by cinimodev** [paolostivanin/OTPClient#371]
Aegis allows users to select custom images from their camera roll as the icon for for service. I was playing around with the feature as a gag. When importing an Aegis encrypted export, OTP Client crashes. I tested with and without custom icons and the custom icon set causes a crash each time. The imports without custom images (or the stock icon) does not crash.

This is not a major issue. Just wanted to pass along the info in case anyone else has this issue.

**Comment by elliotwutingfeng** [comment]
The Aegis android app itself is known to crash with an Out of Memory error when importing vaults with very large custom icons, perhaps this might be related.

**Comment by paolostivanin** [comment]
Thanks for reporting this. I'll have a look at it. If you could provide a simple reproducer, that would be fantastic :smile:

**Comment by paolostivanin** [comment]
The crash is likely to happen because the icons are consuming all the secure memory. Can you tell me whether the custom icons are using a dedicated key or just the usual `icon` key?

**Comment by paolostivanin** [comment]
Could you please try the fix [in this branch](https://github.com/paolostivanin/OTPClient/tree/tryfix) and let me know? Thanks!
