### ISSUE TITLE
Crashes when trying to add TOTP from QR-code

### ISSUE THREAD

**Issue by 413xx0** [paolostivanin/OTPClient#374]
Tried to load QR-code from file and clipboard, both don't work (don't have a webcam)
QR data looks like this: `otpauth://totp/Service:account?secret=some_secret&issuer=Service`
OTPClient logs:
```
double free or corruption (!prev)
zsh: IOT instruction (core dumped)  otpclient
```

OTPClient version: `3.7.0`
Source of installation: AUR package `otpclient`
memlock limits: `unlimited`
OS: `Manjaro 24.0.4 Wynsdey`
Kernel: `x86_64 Linux 6.6.40-1-MANJARO`

**Comment by paolostivanin** [comment]
Thanks for reporting, I'll look into this asap.
