### ISSUE TITLE
File is corrupted error when importing from aegis

### ISSUE THREAD

**Issue by L1so** [paolostivanin/OTPClient#375]
Hello, I get file is corrupted error even though I'm pretty sure I'm entering the right encryption password, the error also happen in un-encrypted exported vault.

![Screenshot_2024-08-02_09-40-47](https://github.com/user-attachments/assets/cdb5498b-80a9-46c5-9ad7-239e20886f8f)

Below is the screencap of the issue.

![Recording 2024-08-02 at 09 42 55](https://github.com/user-attachments/assets/08e5559d-6521-40c2-bccb-69498eb13cd1)

I'm using debian 12

**Comment by paolostivanin** [comment]
are you using the version from the repo, so 3.1.4?

**Comment by L1so** [comment]
Yes correct, I'm using 3.1.4, the latest version seems to only available on debian sid

**Comment by paolostivanin** [comment]
I'm sorry, but that version is way too old and no longer supported. There have been many changes and fixes (especially to Aegis) since that version, so you should take the last one available or ask maintainer to backport it to Debian stable.
Unfortunately, there's nothing I can do about it.
