### ISSUE TITLE
False detection of memory

### ISSUE THREAD

**Issue by lkabuci** [paolostivanin/OTPClient#379]
![Screenshot from 2024-08-12 12-04-38](https://github.com/user-attachments/assets/df55714f-b7f1-47e8-ae58-9e9505557172)

```sh
$> awk '/MemFree/ {print $2/1024 " MB"}' /proc/meminfo
14281.8 MB
```
as you can see i still have enough memory but the program is complaining about it

**Comment by paolostivanin** [comment]
hello,
That's about the memlock limit, not the amount of free ram available to the system.
Please have a look at the wiki for more info!
