### ISSUE TITLE
New versoins in PPA for Ubuntu jammy 22.04

### ISSUE THREAD

**Issue by timur-g** [paolostivanin/OTPClient#381]
Hello. There is PPA for OTPclient, nice. But for Ubuntu jammy 22.04 latest is only 3.4.1.
Is there a reason 4.0.2 ithat is there, is not there also for jammy>

**Comment by paolostivanin** [comment]
hello,
yes. Jammy doesn't have the required libgcrypt version (provided 1.9.4, needed 1.10.1)
