### ISSUE TITLE
Import from Google Authenticator export QR code

### ISSUE THREAD

**Issue by BaruchWeka** [paolostivanin/OTPClient#382]
I'd like to be able to import into OTPClient from the Google Authenticator app, it provides a rather dense QR code for that but that is not supported by the add QR code nor is there support in the import procedure.

**Comment by paolostivanin** [comment]
* what version are you using?
* what OS?
* is it flatpak?

**Comment by BaruchWeka** [comment]
I'm using an ancient version (2.4.6) and can't upgrade, I'll close this ticket since I can't work on it or research for the issue.
