### ISSUE TITLE
QR import needs to show the camera input

### ISSUE THREAD

**Issue by BaruchWeka** [paolostivanin/OTPClient#383]
It is hard to know if the camera is working or not and what distance to use without being able to see the actual camera feed in real time.

I also have two cameras and do not know which one is used by the app and have no way to select it either.

**Comment by paolostivanin** [comment]
The live feed is shown here, I can't reproduce your issue.

* what version are you using?
* what OS?
* is it flatpak?

**Comment by BaruchWeka** [comment]
I'm using Ubuntu 22.0.4.5 with otpclient version 2.4.6-1 from apt and I don't get any video feed or any place that looks like a video feed.

**Comment by BaruchWeka** [comment]
Looks like I'm on an ancient version with the latest being 4.0.1, I'll check that first.

**Comment by BaruchWeka** [comment]
Looks like I'm stuck here, Ubuntu 22 doesn't have the needed dependencies (protobuf at least) to build the latest otpclient. I'll close the ticket.

**Comment by paolostivanin** [comment]
You can use my ppa to get a newer version (still not the latest because of missing does): https://launchpad.net/~polslinux/+archive/ubuntu/otpclient?field.series_filter=jammy
