### ISSUE TITLE
Issues generating codes on Fedora Silverblue 40 and 41

### ISSUE THREAD

**Issue by pluby** [paolostivanin/OTPClient#387]
I'm having problems with codes on Fedora 40 and 41 Silverblue, I think it was since switching to Fedora Silverblue but can't be certain. Note that another TOTP app is also generating incorrect codes, but oddly different codes so it may be a problem with my system but I'm not sure if it might be a flatpak/silverblue issue. Note that for a while some older codes did work but no more. The keys all look OK when used with another app. Any help appreciated.

What I've tried:

- Upgrade entire OS and software.
- Checked the key obtained via the QR code and it matches the one on-screen, it does and works in an FreeOTP on Android.
- Retried many times after waiting for next code.
- Checked hardware clock is UTC and system date/time and timezone are correct (GMT)
- Checked using https://www.verifyr.com/en/otp/check generated codes and the codes generated are not valid.

Any ideas?

Thanks

Version: 4.0.2 (Flathub)

# System Details Report
---

## Report details
- **Date generated:**                              2024-11-12 16:43:49

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkPad T460
- **Memory:**                                      8.0 GiB
- **Processor:**                                   Intel® Core™ i5-6300U × 4
- **Graphics:**                                    Intel® HD Graphics 520 (SKL GT2)
- **Disk Capacity:**                               240.1 GB

## Software Information:
- **Firmware Version:**                            R06ET71W (1.45 )
- **OS Name:**                                     Fedora Linux 41.20241112.0 (Silverblue)
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.7-300.fc41.x86_64

**Comment by pluby** [comment]
Sorry. Ignore this I found a slight time drift that is probably the issue. Not sure what's causing it, but it's not a problem with this software. Sorry again.

**Comment by paolostivanin** [comment]
No problem at all :smile: I'm here if you need me!
