### ISSUE TITLE
Unable to import encrypted andOTP backup

### ISSUE THREAD

**Issue by RaggedStaff** [paolostivanin/OTPClient#388]
Hi

I'm trying to import a GPG encrypted andOTP backup. 

It's prompting for a password but not asking which key to use. It then fails to decrypt the archive.

Does OTPClient support GPG encrypted andOTP backups ? 😕

**Comment by paolostivanin** [comment]
Hello!
Yes, it only supports importing password encrypted backups.
Also, since development has been abandoned a long time ago, it's very likely I will remove andopt support with the next major release.
