### ISSUE TITLE
Import menu disappeared after Flatpak version upgrade to 4.0.2

### ISSUE THREAD

**Issue by b3taman** [paolostivanin/OTPClient#390]
Hi,

After upgrading to the above, there is no import option on the hamburger menu, as per the screenshot.

![No-import](https://github.com/user-attachments/assets/12347b6b-71b7-47c6-98bc-05d56f7a9fa9)

Any ideas? It's a bit of a problem.

8-)
John

**Comment by paolostivanin** [comment]
It's now part of the `+` menu on the left side!

**Comment by b3taman** [comment]
Ah! Thanks, Paulo.

What threw me was the documentation: [Import and Export](https://github.com/paolostivanin/OTPClient/wiki/How-to-use-OTPClient#import-and-export)

**Comment by paolostivanin** [comment]
you're right, I've just fixed it! Thanks a lot for pointing it out :smile:
