### ISSUE TITLE
Explain why you want the password

### ISSUE THREAD

**Issue by nedrichards** [paolostivanin/OTPClient#41]
I installed the OTPClient flatpak and the first thing I was presented with was a dialog window that just asked for my password twice. Now having a read into this a little bit i knew why, and wasn't too distressed but a less educated user would be somewhat disturbed. It might be nice to explain a little more about why you want a password and what it'll be used for.

**Comment by paolostivanin** [comment]
Good point 👍  I'll add a message and will also update also the README with a "How To Use" section.

Thanks!

**Comment by nedrichards** [comment]
While you're on it that dialog would probably be improved by a bit of padding around the buttons, but that's probably not as important as the extra information.

You should also specify *which* password. It took me a second to think! If someone is coming to the tool expecting to use it for google 2fa they might try using their google password for instance.

**Comment by paolostivanin** [comment]
Thanks for your suggestions :) I'll add them all!
