### ISSUE TITLE
add exports (andOTP)

### ISSUE THREAD

**Issue by paolostivanin** [paolostivanin/OTPClient#43]
export data to an encrypted json supported by andOTP

**Comment by magiruuvelvet** [comment]
i implemented this feature in my own OTP C++ library, you can take a look at this file for some hints if you want
[`https://github.com/magiruuvelvet/OTPGen/blob/master/Source/Core/AppSupport/andOTP.cpp`](https://github.com/magiruuvelvet/OTPGen/blob/master/Source/Core/AppSupport/andOTP.cpp)

i used crypto++ though so this steps need to be adjusted for gcrypt

**Comment by curious-jim** [comment]
any news about 1.4.0?

**Comment by paolostivanin** [comment]
@curious-jim I keep updated info about a possible ETA here: https://github.com/paolostivanin/OTPClient/wiki/Roadmap

These past weeks I've been very busy with personal stuff (a lot of changes), that's why you've seen no updates.

I think Feb/Mar is a reasonable ETA for 1.4.0 though :)
