### ISSUE TITLE
Doesn’t work with Amazon

### ISSUE THREAD

**Issue by gergelypolonkai** [paolostivanin/OTPClient#78]
Amazon provides a 32 byte secret (52 characters when Base32 encoded); it seems that OTPClient accepts 14 characters max.

**Comment by paolostivanin** [comment]
Hi, thanks for reporting this.
Are you referring to amazon.`$country` token or the AWS one?

**Comment by gergelypolonkai** [comment]
Aren’t they the same? :) I don’t use AWS, so I guess it’s the Amazon.TLD thing.

**Comment by paolostivanin** [comment]
No, they are two different codes. I have imported both codes successfully in the past, maybe something changed. I'll have a look later today!

**Comment by paolostivanin** [comment]
fixed in develop!
