### ISSUE TITLE
Show checkbox must be ticked to delete a key

### ISSUE THREAD

**Issue by gergelypolonkai** [paolostivanin/OTPClient#79]
After finding out that OTPClient can’t handle Amazon’s secret (reported in #78), I tried to delete the Amazon entry.

* Select the key
* Press the - button on the header bar
* Press Yes on the confirmation dialog

Nothing happened. Out of curiosity I tried a new thing:

* Tick the checkbox
* Press the - button
* Press Yes on the confirmation dialog

And it was deleted.

**Comment by paolostivanin** [comment]
Hi,
yes, that's how it works currently. I will add the possibility to remove selected rows with the next release.

**Comment by paolostivanin** [comment]
I thought about it. Deleting both the ticked and selected rows could be not what the user wants. (maybe some rows are selected by mistake or whatever...)
Moreover, deleting only the selected rows and not the ticked ones could be misleading.

I'll improve the doc though, that for sure.

**Comment by gergelypolonkai** [comment]
Actually (for me) the whole “tick this to show the code” thing was confusing.

For example, I really like how FreeOTP+ works: thereʼs a list of - - - - - - there, and if you touch one of them, it reveals the code, and immediately copies it to the clipboard. Also, a timer starts and when it ends the code gets hidden again.

I donʼt think, however, that this is what you should follow until you redesign the UI with a ListBox. After that it might be a good start (except for the copy to clipboard thing. That should be an explicit user action on a desktop app.)

**Comment by paolostivanin** [comment]
Yep, makes sense. Right now with the treeview and the list store doesn't make any sense (and would be not easy achievable).

And yes, I thought about something like this for the listbox :) let's see how it will look like!

**Comment by paolostivanin** [comment]
It's very unlikely that I will implement something like FreeOTP though. I find annoying that every 30s the token is automatically hidden (maybe when you show it only 6s are left and then you would have to re-click the item again)

**Comment by gergelypolonkai** [comment]
FreeOTP+ shows the token for 30s, even if the token changes. Also, if you
tap the code again, it adds more time.

**Comment by paolostivanin** [comment]
Ah ok, I see. Mmm might be an interesting one to implement...I'll think about it!
