### ISSUE TITLE
 Need 5 Letter* option for Steam

### ISSUE THREAD

**Issue by AnadiaShark** [paolostivanin/OTPClient#86]
Steam authentication uses 5 Letter* rather then 6 or 8

**Comment by paolostivanin** [comment]
Thanks for reporting this! I'll have a look at how Steam Auth works.

**Comment by paolostivanin** [comment]
depends on https://github.com/paolostivanin/libcotp/issues/12 and https://github.com/paolostivanin/libbaseencode/issues/15
