### ISSUE TITLE
Lower GTK+ dependency to 3.18

### ISSUE THREAD

**Issue by dawidd6** [paolostivanin/OTPClient#96]
Hello, can we somehow work around this function:

https://github.com/paolostivanin/OTPClient/blob/8a6733b4114e6641e3254f326ac78dce3c66a433/src/manual-add-cb.c#L126

It's the only one function not available in 3.18. In my xenial packages i just comment this line and i haven't noticed any wrong behavior.

**Comment by paolostivanin** [comment]
Hello,
You didn't notice any wrong behaviour because this is just a cosmetic thing :)
I'll add a ifdef during compile time because it's nice to have this if the needed gtk version is installed :v:

**Comment by dawidd6** [comment]
Sweet, thanks, but wait, there is more.

https://github.com/paolostivanin/OTPClient/blob/8a6733b4114e6641e3254f326ac78dce3c66a433/src/ui/popover.ui#L4

This number should be lowered as well, because it's complaining at runtime.

**Comment by paolostivanin** [comment]
Yep, right :)
